*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: V_TN1TC_CATEGORY................................*
TABLES: V_TN1TC_CATEGORY, *V_TN1TC_CATEGORY. "view work areas
CONTROLS: TCTRL_V_TN1TC_CATEGORY
TYPE TABLEVIEW USING SCREEN '0700'.
DATA: BEGIN OF STATUS_V_TN1TC_CATEGORY. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_V_TN1TC_CATEGORY.
* Table for entries selected to show on screen
DATA: BEGIN OF V_TN1TC_CATEGORY_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_CATEGORY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_CATEGORY_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF V_TN1TC_CATEGORY_TOTAL OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_CATEGORY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_CATEGORY_TOTAL.

*...processing: V_TN1TC_GLOB_SET................................*
TABLES: V_TN1TC_GLOB_SET, *V_TN1TC_GLOB_SET. "view work areas
CONTROLS: TCTRL_V_TN1TC_GLOB_SET
TYPE TABLEVIEW USING SCREEN '0100'.
DATA: BEGIN OF STATUS_V_TN1TC_GLOB_SET. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_V_TN1TC_GLOB_SET.
* Table for entries selected to show on screen
DATA: BEGIN OF V_TN1TC_GLOB_SET_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_GLOB_SET.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_GLOB_SET_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF V_TN1TC_GLOB_SET_TOTAL OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_GLOB_SET.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_GLOB_SET_TOTAL.

*...processing: V_TN1TC_OU_RESP.................................*
TABLES: V_TN1TC_OU_RESP, *V_TN1TC_OU_RESP. "view work areas
CONTROLS: TCTRL_V_TN1TC_OU_RESP
TYPE TABLEVIEW USING SCREEN '0200'.
DATA: BEGIN OF STATUS_V_TN1TC_OU_RESP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_V_TN1TC_OU_RESP.
* Table for entries selected to show on screen
DATA: BEGIN OF V_TN1TC_OU_RESP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_OU_RESP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_OU_RESP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF V_TN1TC_OU_RESP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_OU_RESP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_OU_RESP_TOTAL.

*...processing: V_TN1TC_OU_RP_OU................................*
TABLES: V_TN1TC_OU_RP_OU, *V_TN1TC_OU_RP_OU. "view work areas
CONTROLS: TCTRL_V_TN1TC_OU_RP_OU
TYPE TABLEVIEW USING SCREEN '0300'.
DATA: BEGIN OF STATUS_V_TN1TC_OU_RP_OU. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_V_TN1TC_OU_RP_OU.
* Table for entries selected to show on screen
DATA: BEGIN OF V_TN1TC_OU_RP_OU_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_OU_RP_OU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_OU_RP_OU_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF V_TN1TC_OU_RP_OU_TOTAL OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_OU_RP_OU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_OU_RP_OU_TOTAL.

*...processing: V_TN1TC_RESP_ROL................................*
TABLES: V_TN1TC_RESP_ROL, *V_TN1TC_RESP_ROL. "view work areas
CONTROLS: TCTRL_V_TN1TC_RESP_ROL
TYPE TABLEVIEW USING SCREEN '0400'.
DATA: BEGIN OF STATUS_V_TN1TC_RESP_ROL. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_V_TN1TC_RESP_ROL.
* Table for entries selected to show on screen
DATA: BEGIN OF V_TN1TC_RESP_ROL_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_RESP_ROL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_RESP_ROL_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF V_TN1TC_RESP_ROL_TOTAL OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_RESP_ROL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_RESP_ROL_TOTAL.

*...processing: V_TN1TC_TIMES_IN................................*
TABLES: V_TN1TC_TIMES_IN, *V_TN1TC_TIMES_IN. "view work areas
CONTROLS: TCTRL_V_TN1TC_TIMES_IN
TYPE TABLEVIEW USING SCREEN '0500'.
DATA: BEGIN OF STATUS_V_TN1TC_TIMES_IN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_V_TN1TC_TIMES_IN.
* Table for entries selected to show on screen
DATA: BEGIN OF V_TN1TC_TIMES_IN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_TIMES_IN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_TIMES_IN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF V_TN1TC_TIMES_IN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_TIMES_IN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_TIMES_IN_TOTAL.

*...processing: V_TN1TC_TIMES_OU................................*
TABLES: V_TN1TC_TIMES_OU, *V_TN1TC_TIMES_OU. "view work areas
CONTROLS: TCTRL_V_TN1TC_TIMES_OU
TYPE TABLEVIEW USING SCREEN '0600'.
DATA: BEGIN OF STATUS_V_TN1TC_TIMES_OU. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_V_TN1TC_TIMES_OU.
* Table for entries selected to show on screen
DATA: BEGIN OF V_TN1TC_TIMES_OU_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_TIMES_OU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_TIMES_OU_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF V_TN1TC_TIMES_OU_TOTAL OCCURS 0010.
INCLUDE STRUCTURE V_TN1TC_TIMES_OU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_TN1TC_TIMES_OU_TOTAL.

*.........table declarations:.................................*
TABLES: AGR_DEFINE                     .
TABLES: AGR_TEXTS                      .
TABLES: NORG                           .
TABLES: TN01                           .
TABLES: TN1TC_CATEGORY                 .
TABLES: TN1TC_GLOB_SET                 .
TABLES: TN1TC_OU_RESP                  .
TABLES: TN1TC_OU_RESPT                 .
TABLES: TN1TC_OU_RESP_OU               .
TABLES: TN1TC_RESP_ROLE                .
TABLES: TN1TC_TIMES_INST               .
TABLES: TN1TC_TIMES_OU                 .
