*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: V_TN1TC_CATEGORY................................*
FORM GET_DATA_V_TN1TC_CATEGORY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM TN1TC_CATEGORY WHERE
(VIM_WHERETAB) .
    CLEAR V_TN1TC_CATEGORY .
V_TN1TC_CATEGORY-MANDT =
TN1TC_CATEGORY-MANDT .
V_TN1TC_CATEGORY-SPRAS =
TN1TC_CATEGORY-SPRAS .
V_TN1TC_CATEGORY-INSTITUTION_ID =
TN1TC_CATEGORY-INSTITUTION_ID .
V_TN1TC_CATEGORY-CAT_ORDER =
TN1TC_CATEGORY-CAT_ORDER .
V_TN1TC_CATEGORY-CATEGORY =
TN1TC_CATEGORY-CATEGORY .
V_TN1TC_CATEGORY-JUST_USE =
TN1TC_CATEGORY-JUST_USE .
V_TN1TC_CATEGORY-ERDAT =
TN1TC_CATEGORY-ERDAT .
V_TN1TC_CATEGORY-ERUSR =
TN1TC_CATEGORY-ERUSR .
V_TN1TC_CATEGORY-UPDAT =
TN1TC_CATEGORY-UPDAT .
V_TN1TC_CATEGORY-UPUSR =
TN1TC_CATEGORY-UPUSR .
<VIM_TOTAL_STRUC> = V_TN1TC_CATEGORY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_TN1TC_CATEGORY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_TN1TC_CATEGORY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_TN1TC_CATEGORY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_CATEGORY WHERE
  SPRAS = V_TN1TC_CATEGORY-SPRAS AND
  INSTITUTION_ID = V_TN1TC_CATEGORY-INSTITUTION_ID AND
  CAT_ORDER = V_TN1TC_CATEGORY-CAT_ORDER .
    IF SY-SUBRC = 0.
    DELETE TN1TC_CATEGORY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_CATEGORY WHERE
  SPRAS = V_TN1TC_CATEGORY-SPRAS AND
  INSTITUTION_ID = V_TN1TC_CATEGORY-INSTITUTION_ID AND
  CAT_ORDER = V_TN1TC_CATEGORY-CAT_ORDER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR TN1TC_CATEGORY.
    ENDIF.
TN1TC_CATEGORY-MANDT =
V_TN1TC_CATEGORY-MANDT .
TN1TC_CATEGORY-SPRAS =
V_TN1TC_CATEGORY-SPRAS .
TN1TC_CATEGORY-INSTITUTION_ID =
V_TN1TC_CATEGORY-INSTITUTION_ID .
TN1TC_CATEGORY-CAT_ORDER =
V_TN1TC_CATEGORY-CAT_ORDER .
TN1TC_CATEGORY-CATEGORY =
V_TN1TC_CATEGORY-CATEGORY .
TN1TC_CATEGORY-JUST_USE =
V_TN1TC_CATEGORY-JUST_USE .
TN1TC_CATEGORY-ERDAT =
V_TN1TC_CATEGORY-ERDAT .
TN1TC_CATEGORY-ERUSR =
V_TN1TC_CATEGORY-ERUSR .
TN1TC_CATEGORY-UPDAT =
V_TN1TC_CATEGORY-UPDAT .
TN1TC_CATEGORY-UPUSR =
V_TN1TC_CATEGORY-UPUSR .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_CATEGORY ##WARN_OK.
    ELSE.
    INSERT TN1TC_CATEGORY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_TN1TC_CATEGORY-UPD_FLAG,
STATUS_V_TN1TC_CATEGORY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_TN1TC_CATEGORY.
  SELECT SINGLE * FROM TN1TC_CATEGORY WHERE
SPRAS = V_TN1TC_CATEGORY-SPRAS AND
INSTITUTION_ID = V_TN1TC_CATEGORY-INSTITUTION_ID AND
CAT_ORDER = V_TN1TC_CATEGORY-CAT_ORDER .
V_TN1TC_CATEGORY-MANDT =
TN1TC_CATEGORY-MANDT .
V_TN1TC_CATEGORY-SPRAS =
TN1TC_CATEGORY-SPRAS .
V_TN1TC_CATEGORY-INSTITUTION_ID =
TN1TC_CATEGORY-INSTITUTION_ID .
V_TN1TC_CATEGORY-CAT_ORDER =
TN1TC_CATEGORY-CAT_ORDER .
V_TN1TC_CATEGORY-CATEGORY =
TN1TC_CATEGORY-CATEGORY .
V_TN1TC_CATEGORY-JUST_USE =
TN1TC_CATEGORY-JUST_USE .
V_TN1TC_CATEGORY-ERDAT =
TN1TC_CATEGORY-ERDAT .
V_TN1TC_CATEGORY-ERUSR =
TN1TC_CATEGORY-ERUSR .
V_TN1TC_CATEGORY-UPDAT =
TN1TC_CATEGORY-UPDAT .
V_TN1TC_CATEGORY-UPUSR =
TN1TC_CATEGORY-UPUSR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_TN1TC_CATEGORY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_TN1TC_CATEGORY-SPRAS TO
TN1TC_CATEGORY-SPRAS .
MOVE V_TN1TC_CATEGORY-INSTITUTION_ID TO
TN1TC_CATEGORY-INSTITUTION_ID .
MOVE V_TN1TC_CATEGORY-CAT_ORDER TO
TN1TC_CATEGORY-CAT_ORDER .
MOVE V_TN1TC_CATEGORY-MANDT TO
TN1TC_CATEGORY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_CATEGORY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_CATEGORY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_CATEGORY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: V_TN1TC_GLOB_SET................................*
FORM GET_DATA_V_TN1TC_GLOB_SET.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM TN1TC_GLOB_SET WHERE
(VIM_WHERETAB) .
    CLEAR V_TN1TC_GLOB_SET .
V_TN1TC_GLOB_SET-MANDT =
TN1TC_GLOB_SET-MANDT .
V_TN1TC_GLOB_SET-INSTITUTION_ID =
TN1TC_GLOB_SET-INSTITUTION_ID .
V_TN1TC_GLOB_SET-SECURITY_LEVEL =
TN1TC_GLOB_SET-SECURITY_LEVEL .
V_TN1TC_GLOB_SET-DECAY_TIME =
TN1TC_GLOB_SET-DECAY_TIME .
V_TN1TC_GLOB_SET-ERDAT =
TN1TC_GLOB_SET-ERDAT .
V_TN1TC_GLOB_SET-ERUSR =
TN1TC_GLOB_SET-ERUSR .
V_TN1TC_GLOB_SET-UPDAT =
TN1TC_GLOB_SET-UPDAT .
V_TN1TC_GLOB_SET-UPUSR =
TN1TC_GLOB_SET-UPUSR .
V_TN1TC_GLOB_SET-NO_CLEAR_BUFFER =
TN1TC_GLOB_SET-NO_CLEAR_BUFFER .
V_TN1TC_GLOB_SET-INACTIVE_DAYS =
TN1TC_GLOB_SET-INACTIVE_DAYS .
V_TN1TC_GLOB_SET-ALTERNATIV_MATRIX =
TN1TC_GLOB_SET-ALTERNATIV_MATRIX .
V_TN1TC_GLOB_SET-LEAD_TIME =
TN1TC_GLOB_SET-LEAD_TIME .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_GLOB_SET-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_GLOB_SET-EINKB =
TN01-EINKB .
    ENDIF.
<VIM_TOTAL_STRUC> = V_TN1TC_GLOB_SET.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_TN1TC_GLOB_SET .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_TN1TC_GLOB_SET.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_TN1TC_GLOB_SET-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_GLOB_SET WHERE
  INSTITUTION_ID = V_TN1TC_GLOB_SET-INSTITUTION_ID .
    IF SY-SUBRC = 0.
    DELETE TN1TC_GLOB_SET .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_GLOB_SET WHERE
  INSTITUTION_ID = V_TN1TC_GLOB_SET-INSTITUTION_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR TN1TC_GLOB_SET.
    ENDIF.
TN1TC_GLOB_SET-MANDT =
V_TN1TC_GLOB_SET-MANDT .
TN1TC_GLOB_SET-INSTITUTION_ID =
V_TN1TC_GLOB_SET-INSTITUTION_ID .
TN1TC_GLOB_SET-SECURITY_LEVEL =
V_TN1TC_GLOB_SET-SECURITY_LEVEL .
TN1TC_GLOB_SET-DECAY_TIME =
V_TN1TC_GLOB_SET-DECAY_TIME .
TN1TC_GLOB_SET-ERDAT =
V_TN1TC_GLOB_SET-ERDAT .
TN1TC_GLOB_SET-ERUSR =
V_TN1TC_GLOB_SET-ERUSR .
TN1TC_GLOB_SET-UPDAT =
V_TN1TC_GLOB_SET-UPDAT .
TN1TC_GLOB_SET-UPUSR =
V_TN1TC_GLOB_SET-UPUSR .
TN1TC_GLOB_SET-NO_CLEAR_BUFFER =
V_TN1TC_GLOB_SET-NO_CLEAR_BUFFER .
TN1TC_GLOB_SET-INACTIVE_DAYS =
V_TN1TC_GLOB_SET-INACTIVE_DAYS .
TN1TC_GLOB_SET-ALTERNATIV_MATRIX =
V_TN1TC_GLOB_SET-ALTERNATIV_MATRIX .
TN1TC_GLOB_SET-LEAD_TIME =
V_TN1TC_GLOB_SET-LEAD_TIME .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_GLOB_SET ##WARN_OK.
    ELSE.
    INSERT TN1TC_GLOB_SET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_TN1TC_GLOB_SET-UPD_FLAG,
STATUS_V_TN1TC_GLOB_SET-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_TN1TC_GLOB_SET.
  SELECT SINGLE * FROM TN1TC_GLOB_SET WHERE
INSTITUTION_ID = V_TN1TC_GLOB_SET-INSTITUTION_ID .
V_TN1TC_GLOB_SET-MANDT =
TN1TC_GLOB_SET-MANDT .
V_TN1TC_GLOB_SET-INSTITUTION_ID =
TN1TC_GLOB_SET-INSTITUTION_ID .
V_TN1TC_GLOB_SET-SECURITY_LEVEL =
TN1TC_GLOB_SET-SECURITY_LEVEL .
V_TN1TC_GLOB_SET-DECAY_TIME =
TN1TC_GLOB_SET-DECAY_TIME .
V_TN1TC_GLOB_SET-ERDAT =
TN1TC_GLOB_SET-ERDAT .
V_TN1TC_GLOB_SET-ERUSR =
TN1TC_GLOB_SET-ERUSR .
V_TN1TC_GLOB_SET-UPDAT =
TN1TC_GLOB_SET-UPDAT .
V_TN1TC_GLOB_SET-UPUSR =
TN1TC_GLOB_SET-UPUSR .
V_TN1TC_GLOB_SET-NO_CLEAR_BUFFER =
TN1TC_GLOB_SET-NO_CLEAR_BUFFER .
V_TN1TC_GLOB_SET-INACTIVE_DAYS =
TN1TC_GLOB_SET-INACTIVE_DAYS .
V_TN1TC_GLOB_SET-ALTERNATIV_MATRIX =
TN1TC_GLOB_SET-ALTERNATIV_MATRIX .
V_TN1TC_GLOB_SET-LEAD_TIME =
TN1TC_GLOB_SET-LEAD_TIME .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_GLOB_SET-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_GLOB_SET-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_GLOB_SET-EINKB .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_TN1TC_GLOB_SET USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_TN1TC_GLOB_SET-INSTITUTION_ID TO
TN1TC_GLOB_SET-INSTITUTION_ID .
MOVE V_TN1TC_GLOB_SET-MANDT TO
TN1TC_GLOB_SET-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_GLOB_SET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_GLOB_SET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_GLOB_SET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_V_TN1TC_GLOB_SET USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
TN1TC_GLOB_SET-MANDT =
V_TN1TC_GLOB_SET-MANDT .
TN1TC_GLOB_SET-INSTITUTION_ID =
V_TN1TC_GLOB_SET-INSTITUTION_ID .
TN1TC_GLOB_SET-SECURITY_LEVEL =
V_TN1TC_GLOB_SET-SECURITY_LEVEL .
TN1TC_GLOB_SET-DECAY_TIME =
V_TN1TC_GLOB_SET-DECAY_TIME .
TN1TC_GLOB_SET-ERDAT =
V_TN1TC_GLOB_SET-ERDAT .
TN1TC_GLOB_SET-ERUSR =
V_TN1TC_GLOB_SET-ERUSR .
TN1TC_GLOB_SET-UPDAT =
V_TN1TC_GLOB_SET-UPDAT .
TN1TC_GLOB_SET-UPUSR =
V_TN1TC_GLOB_SET-UPUSR .
TN1TC_GLOB_SET-NO_CLEAR_BUFFER =
V_TN1TC_GLOB_SET-NO_CLEAR_BUFFER .
TN1TC_GLOB_SET-INACTIVE_DAYS =
V_TN1TC_GLOB_SET-INACTIVE_DAYS .
TN1TC_GLOB_SET-ALTERNATIV_MATRIX =
V_TN1TC_GLOB_SET-ALTERNATIV_MATRIX .
TN1TC_GLOB_SET-LEAD_TIME =
V_TN1TC_GLOB_SET-LEAD_TIME .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_GLOB_SET-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_GLOB_SET-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_GLOB_SET-EINKB .
    ENDIF.
ENDFORM.
*...processing: V_TN1TC_OU_RESP.................................*
FORM GET_DATA_V_TN1TC_OU_RESP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM TN1TC_OU_RESP WHERE
(VIM_WHERETAB) .
    CLEAR V_TN1TC_OU_RESP .
V_TN1TC_OU_RESP-MANDT =
TN1TC_OU_RESP-MANDT .
V_TN1TC_OU_RESP-OU_RESP =
TN1TC_OU_RESP-OU_RESP .
V_TN1TC_OU_RESP-RESP_TYPE =
TN1TC_OU_RESP-RESP_TYPE .
    SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RESP-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
V_TN1TC_OU_RESP-ERDAT =
TN1TC_OU_RESPT-ERDAT .
V_TN1TC_OU_RESP-ERUSR =
TN1TC_OU_RESPT-ERUSR .
V_TN1TC_OU_RESP-UPDAT =
TN1TC_OU_RESPT-UPDAT .
V_TN1TC_OU_RESP-UPUSR =
TN1TC_OU_RESPT-UPUSR .
    ENDIF.
<VIM_TOTAL_STRUC> = V_TN1TC_OU_RESP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_TN1TC_OU_RESP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_TN1TC_OU_RESP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_TN1TC_OU_RESP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_OU_RESP WHERE
  OU_RESP = V_TN1TC_OU_RESP-OU_RESP .
    IF SY-SUBRC = 0.
    DELETE TN1TC_OU_RESP .
    ENDIF.
    DELETE FROM TN1TC_OU_RESPT WHERE
    OU_RESP = TN1TC_OU_RESP-OU_RESP .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_OU_RESP WHERE
  OU_RESP = V_TN1TC_OU_RESP-OU_RESP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR TN1TC_OU_RESP.
    ENDIF.
TN1TC_OU_RESP-MANDT =
V_TN1TC_OU_RESP-MANDT .
TN1TC_OU_RESP-OU_RESP =
V_TN1TC_OU_RESP-OU_RESP .
TN1TC_OU_RESP-RESP_TYPE =
V_TN1TC_OU_RESP-RESP_TYPE .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_OU_RESP ##WARN_OK.
    ELSE.
    INSERT TN1TC_OU_RESP .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM TN1TC_OU_RESPT WHERE
    OU_RESP = TN1TC_OU_RESP-OU_RESP AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR TN1TC_OU_RESPT.
TN1TC_OU_RESPT-OU_RESP =
TN1TC_OU_RESP-OU_RESP .
TN1TC_OU_RESPT-LANGU =
SY-LANGU .
      ENDIF.
TN1TC_OU_RESPT-OU_RESP_TEXT =
V_TN1TC_OU_RESP-OU_RESP_TEXT .
TN1TC_OU_RESPT-ERDAT =
V_TN1TC_OU_RESP-ERDAT .
TN1TC_OU_RESPT-ERUSR =
V_TN1TC_OU_RESP-ERUSR .
TN1TC_OU_RESPT-UPDAT =
V_TN1TC_OU_RESP-UPDAT .
TN1TC_OU_RESPT-UPUSR =
V_TN1TC_OU_RESP-UPUSR .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_OU_RESPT ##WARN_OK.
    ELSE.
    INSERT TN1TC_OU_RESPT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_TN1TC_OU_RESP-UPD_FLAG,
STATUS_V_TN1TC_OU_RESP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_TN1TC_OU_RESP.
  SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = V_TN1TC_OU_RESP-OU_RESP .
V_TN1TC_OU_RESP-MANDT =
TN1TC_OU_RESP-MANDT .
V_TN1TC_OU_RESP-OU_RESP =
TN1TC_OU_RESP-OU_RESP .
V_TN1TC_OU_RESP-RESP_TYPE =
TN1TC_OU_RESP-RESP_TYPE .
    SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RESP-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
V_TN1TC_OU_RESP-ERDAT =
TN1TC_OU_RESPT-ERDAT .
V_TN1TC_OU_RESP-ERUSR =
TN1TC_OU_RESPT-ERUSR .
V_TN1TC_OU_RESP-UPDAT =
TN1TC_OU_RESPT-UPDAT .
V_TN1TC_OU_RESP-UPUSR =
TN1TC_OU_RESPT-UPUSR .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_OU_RESP-OU_RESP_TEXT .
      CLEAR V_TN1TC_OU_RESP-ERDAT .
      CLEAR V_TN1TC_OU_RESP-ERUSR .
      CLEAR V_TN1TC_OU_RESP-UPDAT .
      CLEAR V_TN1TC_OU_RESP-UPUSR .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_TN1TC_OU_RESP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_TN1TC_OU_RESP-OU_RESP TO
TN1TC_OU_RESP-OU_RESP .
MOVE V_TN1TC_OU_RESP-MANDT TO
TN1TC_OU_RESP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_OU_RESP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_OU_RESP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_OU_RESP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE TN1TC_OU_RESP-OU_RESP TO
TN1TC_OU_RESPT-OU_RESP .
MOVE SY-LANGU TO
TN1TC_OU_RESPT-LANGU .
MOVE V_TN1TC_OU_RESP-MANDT TO
TN1TC_OU_RESPT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_OU_RESPT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_OU_RESPT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_OU_RESPT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: V_TN1TC_OU_RP_OU................................*
FORM GET_DATA_V_TN1TC_OU_RP_OU.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM TN1TC_OU_RESP_OU WHERE
(VIM_WHERETAB) .
    CLEAR V_TN1TC_OU_RP_OU .
V_TN1TC_OU_RP_OU-MANDT =
TN1TC_OU_RESP_OU-MANDT .
V_TN1TC_OU_RP_OU-INSTITUTION_ID =
TN1TC_OU_RESP_OU-INSTITUTION_ID .
V_TN1TC_OU_RP_OU-OU_RESP =
TN1TC_OU_RESP_OU-OU_RESP .
V_TN1TC_OU_RP_OU-DEPTOU =
TN1TC_OU_RESP_OU-DEPTOU .
V_TN1TC_OU_RP_OU-TREAOU =
TN1TC_OU_RESP_OU-TREAOU .
V_TN1TC_OU_RP_OU-DELFLAG =
TN1TC_OU_RESP_OU-DELFLAG .
V_TN1TC_OU_RP_OU-DELDAT =
TN1TC_OU_RESP_OU-DELDAT .
V_TN1TC_OU_RP_OU-DELUSR =
TN1TC_OU_RESP_OU-DELUSR .
V_TN1TC_OU_RP_OU-ERDAT =
TN1TC_OU_RESP_OU-ERDAT .
V_TN1TC_OU_RP_OU-ERUSR =
TN1TC_OU_RESP_OU-ERUSR .
V_TN1TC_OU_RP_OU-UPDAT =
TN1TC_OU_RESP_OU-UPDAT .
V_TN1TC_OU_RP_OU-UPUSR =
TN1TC_OU_RESP_OU-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_OU_RESP_OU-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-EINKB =
TN01-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_OU_RESP_OU-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM NORG WHERE
ORGID = TN1TC_OU_RESP_OU-DEPTOU .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-DEPTOU_KB =
NORG-ORGKB .
V_TN1TC_OU_RP_OU-TREAOU_KB =
NORG-ORGKB .
    ENDIF.
<VIM_TOTAL_STRUC> = V_TN1TC_OU_RP_OU.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_TN1TC_OU_RP_OU .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_TN1TC_OU_RP_OU.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_TN1TC_OU_RP_OU-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_OU_RESP_OU WHERE
  INSTITUTION_ID = V_TN1TC_OU_RP_OU-INSTITUTION_ID AND
  OU_RESP = V_TN1TC_OU_RP_OU-OU_RESP AND
  DEPTOU = V_TN1TC_OU_RP_OU-DEPTOU AND
  TREAOU = V_TN1TC_OU_RP_OU-TREAOU .
    IF SY-SUBRC = 0.
    DELETE TN1TC_OU_RESP_OU .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_OU_RESP_OU WHERE
  INSTITUTION_ID = V_TN1TC_OU_RP_OU-INSTITUTION_ID AND
  OU_RESP = V_TN1TC_OU_RP_OU-OU_RESP AND
  DEPTOU = V_TN1TC_OU_RP_OU-DEPTOU AND
  TREAOU = V_TN1TC_OU_RP_OU-TREAOU .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR TN1TC_OU_RESP_OU.
    ENDIF.
TN1TC_OU_RESP_OU-MANDT =
V_TN1TC_OU_RP_OU-MANDT .
TN1TC_OU_RESP_OU-INSTITUTION_ID =
V_TN1TC_OU_RP_OU-INSTITUTION_ID .
TN1TC_OU_RESP_OU-OU_RESP =
V_TN1TC_OU_RP_OU-OU_RESP .
TN1TC_OU_RESP_OU-DEPTOU =
V_TN1TC_OU_RP_OU-DEPTOU .
TN1TC_OU_RESP_OU-TREAOU =
V_TN1TC_OU_RP_OU-TREAOU .
TN1TC_OU_RESP_OU-DELFLAG =
V_TN1TC_OU_RP_OU-DELFLAG .
TN1TC_OU_RESP_OU-DELDAT =
V_TN1TC_OU_RP_OU-DELDAT .
TN1TC_OU_RESP_OU-DELUSR =
V_TN1TC_OU_RP_OU-DELUSR .
TN1TC_OU_RESP_OU-ERDAT =
V_TN1TC_OU_RP_OU-ERDAT .
TN1TC_OU_RESP_OU-ERUSR =
V_TN1TC_OU_RP_OU-ERUSR .
TN1TC_OU_RESP_OU-UPDAT =
V_TN1TC_OU_RP_OU-UPDAT .
TN1TC_OU_RESP_OU-UPUSR =
V_TN1TC_OU_RP_OU-UPUSR .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_OU_RESP_OU ##WARN_OK.
    ELSE.
    INSERT TN1TC_OU_RESP_OU .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_TN1TC_OU_RP_OU-UPD_FLAG,
STATUS_V_TN1TC_OU_RP_OU-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_TN1TC_OU_RP_OU.
  SELECT SINGLE * FROM TN1TC_OU_RESP_OU WHERE
INSTITUTION_ID = V_TN1TC_OU_RP_OU-INSTITUTION_ID AND
OU_RESP = V_TN1TC_OU_RP_OU-OU_RESP AND
DEPTOU = V_TN1TC_OU_RP_OU-DEPTOU AND
TREAOU = V_TN1TC_OU_RP_OU-TREAOU .
V_TN1TC_OU_RP_OU-MANDT =
TN1TC_OU_RESP_OU-MANDT .
V_TN1TC_OU_RP_OU-INSTITUTION_ID =
TN1TC_OU_RESP_OU-INSTITUTION_ID .
V_TN1TC_OU_RP_OU-OU_RESP =
TN1TC_OU_RESP_OU-OU_RESP .
V_TN1TC_OU_RP_OU-DEPTOU =
TN1TC_OU_RESP_OU-DEPTOU .
V_TN1TC_OU_RP_OU-TREAOU =
TN1TC_OU_RESP_OU-TREAOU .
V_TN1TC_OU_RP_OU-DELFLAG =
TN1TC_OU_RESP_OU-DELFLAG .
V_TN1TC_OU_RP_OU-DELDAT =
TN1TC_OU_RESP_OU-DELDAT .
V_TN1TC_OU_RP_OU-DELUSR =
TN1TC_OU_RESP_OU-DELUSR .
V_TN1TC_OU_RP_OU-ERDAT =
TN1TC_OU_RESP_OU-ERDAT .
V_TN1TC_OU_RP_OU-ERUSR =
TN1TC_OU_RESP_OU-ERUSR .
V_TN1TC_OU_RP_OU-UPDAT =
TN1TC_OU_RESP_OU-UPDAT .
V_TN1TC_OU_RP_OU-UPUSR =
TN1TC_OU_RESP_OU-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_OU_RESP_OU-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_OU_RP_OU-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_OU_RESP_OU-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_OU_RP_OU-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_OU_RP_OU-OU_RESP_TEXT .
    ENDIF.
    SELECT SINGLE * FROM NORG WHERE
ORGID = TN1TC_OU_RESP_OU-DEPTOU .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-DEPTOU_KB =
NORG-ORGKB .
V_TN1TC_OU_RP_OU-TREAOU_KB =
NORG-ORGKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_OU_RP_OU-DEPTOU_KB .
      CLEAR V_TN1TC_OU_RP_OU-TREAOU_KB .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_TN1TC_OU_RP_OU USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_TN1TC_OU_RP_OU-INSTITUTION_ID TO
TN1TC_OU_RESP_OU-INSTITUTION_ID .
MOVE V_TN1TC_OU_RP_OU-OU_RESP TO
TN1TC_OU_RESP_OU-OU_RESP .
MOVE V_TN1TC_OU_RP_OU-DEPTOU TO
TN1TC_OU_RESP_OU-DEPTOU .
MOVE V_TN1TC_OU_RP_OU-TREAOU TO
TN1TC_OU_RESP_OU-TREAOU .
MOVE V_TN1TC_OU_RP_OU-MANDT TO
TN1TC_OU_RESP_OU-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_OU_RESP_OU'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_OU_RESP_OU TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_OU_RESP_OU'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_V_TN1TC_OU_RP_OU USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
TN1TC_OU_RESP_OU-MANDT =
V_TN1TC_OU_RP_OU-MANDT .
TN1TC_OU_RESP_OU-INSTITUTION_ID =
V_TN1TC_OU_RP_OU-INSTITUTION_ID .
TN1TC_OU_RESP_OU-OU_RESP =
V_TN1TC_OU_RP_OU-OU_RESP .
TN1TC_OU_RESP_OU-DEPTOU =
V_TN1TC_OU_RP_OU-DEPTOU .
TN1TC_OU_RESP_OU-TREAOU =
V_TN1TC_OU_RP_OU-TREAOU .
TN1TC_OU_RESP_OU-DELFLAG =
V_TN1TC_OU_RP_OU-DELFLAG .
TN1TC_OU_RESP_OU-DELDAT =
V_TN1TC_OU_RP_OU-DELDAT .
TN1TC_OU_RESP_OU-DELUSR =
V_TN1TC_OU_RP_OU-DELUSR .
TN1TC_OU_RESP_OU-ERDAT =
V_TN1TC_OU_RP_OU-ERDAT .
TN1TC_OU_RESP_OU-ERUSR =
V_TN1TC_OU_RP_OU-ERUSR .
TN1TC_OU_RESP_OU-UPDAT =
V_TN1TC_OU_RP_OU-UPDAT .
TN1TC_OU_RESP_OU-UPUSR =
V_TN1TC_OU_RP_OU-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_OU_RESP_OU-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_OU_RP_OU-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_OU_RESP_OU-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_OU_RP_OU-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_OU_RP_OU-OU_RESP_TEXT .
    ENDIF.
    SELECT SINGLE * FROM NORG WHERE
ORGID = TN1TC_OU_RESP_OU-DEPTOU .
    IF SY-SUBRC EQ 0.
V_TN1TC_OU_RP_OU-DEPTOU_KB =
NORG-ORGKB .
V_TN1TC_OU_RP_OU-TREAOU_KB =
NORG-ORGKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_OU_RP_OU-DEPTOU_KB .
      CLEAR V_TN1TC_OU_RP_OU-TREAOU_KB .
    ENDIF.
ENDFORM.
*...processing: V_TN1TC_RESP_ROL................................*
FORM GET_DATA_V_TN1TC_RESP_ROL.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM TN1TC_RESP_ROLE WHERE
(VIM_WHERETAB) .
    CLEAR V_TN1TC_RESP_ROL .
V_TN1TC_RESP_ROL-MANDT =
TN1TC_RESP_ROLE-MANDT .
V_TN1TC_RESP_ROL-AGR_NAME =
TN1TC_RESP_ROLE-AGR_NAME .
V_TN1TC_RESP_ROL-OU_RESP =
TN1TC_RESP_ROLE-OU_RESP .
V_TN1TC_RESP_ROL-BEGDT =
TN1TC_RESP_ROLE-BEGDT .
V_TN1TC_RESP_ROL-ENDDT =
TN1TC_RESP_ROLE-ENDDT .
V_TN1TC_RESP_ROL-ERDAT =
TN1TC_RESP_ROLE-ERDAT .
V_TN1TC_RESP_ROL-ERUSR =
TN1TC_RESP_ROLE-ERUSR .
V_TN1TC_RESP_ROL-UPDAT =
TN1TC_RESP_ROLE-UPDAT .
V_TN1TC_RESP_ROL-UPUSR =
TN1TC_RESP_ROLE-UPUSR .
    SELECT SINGLE * FROM AGR_DEFINE WHERE
AGR_NAME = TN1TC_RESP_ROLE-AGR_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM AGR_TEXTS WHERE
AGR_NAME = AGR_DEFINE-AGR_NAME AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_RESP_ROL-LINE =
AGR_TEXTS-LINE .
V_TN1TC_RESP_ROL-TEXT =
AGR_TEXTS-TEXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_RESP_ROLE-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_RESP_ROL-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = V_TN1TC_RESP_ROL.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_TN1TC_RESP_ROL .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_TN1TC_RESP_ROL.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_TN1TC_RESP_ROL-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_RESP_ROLE WHERE
  AGR_NAME = V_TN1TC_RESP_ROL-AGR_NAME AND
  OU_RESP = V_TN1TC_RESP_ROL-OU_RESP AND
  BEGDT = V_TN1TC_RESP_ROL-BEGDT .
    IF SY-SUBRC = 0.
    DELETE TN1TC_RESP_ROLE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_RESP_ROLE WHERE
  AGR_NAME = V_TN1TC_RESP_ROL-AGR_NAME AND
  OU_RESP = V_TN1TC_RESP_ROL-OU_RESP AND
  BEGDT = V_TN1TC_RESP_ROL-BEGDT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR TN1TC_RESP_ROLE.
    ENDIF.
TN1TC_RESP_ROLE-MANDT =
V_TN1TC_RESP_ROL-MANDT .
TN1TC_RESP_ROLE-AGR_NAME =
V_TN1TC_RESP_ROL-AGR_NAME .
TN1TC_RESP_ROLE-OU_RESP =
V_TN1TC_RESP_ROL-OU_RESP .
TN1TC_RESP_ROLE-BEGDT =
V_TN1TC_RESP_ROL-BEGDT .
TN1TC_RESP_ROLE-ENDDT =
V_TN1TC_RESP_ROL-ENDDT .
TN1TC_RESP_ROLE-ERDAT =
V_TN1TC_RESP_ROL-ERDAT .
TN1TC_RESP_ROLE-ERUSR =
V_TN1TC_RESP_ROL-ERUSR .
TN1TC_RESP_ROLE-UPDAT =
V_TN1TC_RESP_ROL-UPDAT .
TN1TC_RESP_ROLE-UPUSR =
V_TN1TC_RESP_ROL-UPUSR .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_RESP_ROLE ##WARN_OK.
    ELSE.
    INSERT TN1TC_RESP_ROLE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_TN1TC_RESP_ROL-UPD_FLAG,
STATUS_V_TN1TC_RESP_ROL-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_TN1TC_RESP_ROL.
  SELECT SINGLE * FROM TN1TC_RESP_ROLE WHERE
AGR_NAME = V_TN1TC_RESP_ROL-AGR_NAME AND
OU_RESP = V_TN1TC_RESP_ROL-OU_RESP AND
BEGDT = V_TN1TC_RESP_ROL-BEGDT .
V_TN1TC_RESP_ROL-MANDT =
TN1TC_RESP_ROLE-MANDT .
V_TN1TC_RESP_ROL-AGR_NAME =
TN1TC_RESP_ROLE-AGR_NAME .
V_TN1TC_RESP_ROL-OU_RESP =
TN1TC_RESP_ROLE-OU_RESP .
V_TN1TC_RESP_ROL-BEGDT =
TN1TC_RESP_ROLE-BEGDT .
V_TN1TC_RESP_ROL-ENDDT =
TN1TC_RESP_ROLE-ENDDT .
V_TN1TC_RESP_ROL-ERDAT =
TN1TC_RESP_ROLE-ERDAT .
V_TN1TC_RESP_ROL-ERUSR =
TN1TC_RESP_ROLE-ERUSR .
V_TN1TC_RESP_ROL-UPDAT =
TN1TC_RESP_ROLE-UPDAT .
V_TN1TC_RESP_ROL-UPUSR =
TN1TC_RESP_ROLE-UPUSR .
    SELECT SINGLE * FROM AGR_DEFINE WHERE
AGR_NAME = TN1TC_RESP_ROLE-AGR_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM AGR_TEXTS WHERE
AGR_NAME = AGR_DEFINE-AGR_NAME AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_RESP_ROL-LINE =
AGR_TEXTS-LINE .
V_TN1TC_RESP_ROL-TEXT =
AGR_TEXTS-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_RESP_ROL-LINE .
        CLEAR V_TN1TC_RESP_ROL-TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_RESP_ROL-LINE .
      CLEAR V_TN1TC_RESP_ROL-TEXT .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_RESP_ROLE-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_RESP_ROL-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_RESP_ROL-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_RESP_ROL-OU_RESP_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_TN1TC_RESP_ROL USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_TN1TC_RESP_ROL-AGR_NAME TO
TN1TC_RESP_ROLE-AGR_NAME .
MOVE V_TN1TC_RESP_ROL-OU_RESP TO
TN1TC_RESP_ROLE-OU_RESP .
MOVE V_TN1TC_RESP_ROL-BEGDT TO
TN1TC_RESP_ROLE-BEGDT .
MOVE V_TN1TC_RESP_ROL-MANDT TO
TN1TC_RESP_ROLE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_RESP_ROLE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_RESP_ROLE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_RESP_ROLE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_V_TN1TC_RESP_ROL USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
TN1TC_RESP_ROLE-MANDT =
V_TN1TC_RESP_ROL-MANDT .
TN1TC_RESP_ROLE-AGR_NAME =
V_TN1TC_RESP_ROL-AGR_NAME .
TN1TC_RESP_ROLE-OU_RESP =
V_TN1TC_RESP_ROL-OU_RESP .
TN1TC_RESP_ROLE-BEGDT =
V_TN1TC_RESP_ROL-BEGDT .
TN1TC_RESP_ROLE-ENDDT =
V_TN1TC_RESP_ROL-ENDDT .
TN1TC_RESP_ROLE-ERDAT =
V_TN1TC_RESP_ROL-ERDAT .
TN1TC_RESP_ROLE-ERUSR =
V_TN1TC_RESP_ROL-ERUSR .
TN1TC_RESP_ROLE-UPDAT =
V_TN1TC_RESP_ROL-UPDAT .
TN1TC_RESP_ROLE-UPUSR =
V_TN1TC_RESP_ROL-UPUSR .
    SELECT SINGLE * FROM AGR_DEFINE WHERE
AGR_NAME = TN1TC_RESP_ROLE-AGR_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM AGR_TEXTS WHERE
AGR_NAME = AGR_DEFINE-AGR_NAME AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_RESP_ROL-LINE =
AGR_TEXTS-LINE .
V_TN1TC_RESP_ROL-TEXT =
AGR_TEXTS-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_RESP_ROL-LINE .
        CLEAR V_TN1TC_RESP_ROL-TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_RESP_ROL-LINE .
      CLEAR V_TN1TC_RESP_ROL-TEXT .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_RESP_ROLE-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_RESP_ROL-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_RESP_ROL-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_RESP_ROL-OU_RESP_TEXT .
    ENDIF.
ENDFORM.
*...processing: V_TN1TC_TIMES_IN................................*
FORM GET_DATA_V_TN1TC_TIMES_IN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM TN1TC_TIMES_INST WHERE
(VIM_WHERETAB) .
    CLEAR V_TN1TC_TIMES_IN .
V_TN1TC_TIMES_IN-MANDT =
TN1TC_TIMES_INST-MANDT .
V_TN1TC_TIMES_IN-INSTITUTION_ID =
TN1TC_TIMES_INST-INSTITUTION_ID .
V_TN1TC_TIMES_IN-OU_RESP =
TN1TC_TIMES_INST-OU_RESP .
V_TN1TC_TIMES_IN-DAYS_EXT =
TN1TC_TIMES_INST-DAYS_EXT .
V_TN1TC_TIMES_IN-DAYS_APPL =
TN1TC_TIMES_INST-DAYS_APPL .
V_TN1TC_TIMES_IN-ERDAT =
TN1TC_TIMES_INST-ERDAT .
V_TN1TC_TIMES_IN-ERUSR =
TN1TC_TIMES_INST-ERUSR .
V_TN1TC_TIMES_IN-UPDAT =
TN1TC_TIMES_INST-UPDAT .
V_TN1TC_TIMES_IN-UPUSR =
TN1TC_TIMES_INST-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_TIMES_INST-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_IN-EINKB =
TN01-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_TIMES_INST-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_IN-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = V_TN1TC_TIMES_IN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_TN1TC_TIMES_IN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_TN1TC_TIMES_IN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_TN1TC_TIMES_IN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_TIMES_INST WHERE
  INSTITUTION_ID = V_TN1TC_TIMES_IN-INSTITUTION_ID AND
  OU_RESP = V_TN1TC_TIMES_IN-OU_RESP .
    IF SY-SUBRC = 0.
    DELETE TN1TC_TIMES_INST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_TIMES_INST WHERE
  INSTITUTION_ID = V_TN1TC_TIMES_IN-INSTITUTION_ID AND
  OU_RESP = V_TN1TC_TIMES_IN-OU_RESP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR TN1TC_TIMES_INST.
    ENDIF.
TN1TC_TIMES_INST-MANDT =
V_TN1TC_TIMES_IN-MANDT .
TN1TC_TIMES_INST-INSTITUTION_ID =
V_TN1TC_TIMES_IN-INSTITUTION_ID .
TN1TC_TIMES_INST-OU_RESP =
V_TN1TC_TIMES_IN-OU_RESP .
TN1TC_TIMES_INST-DAYS_EXT =
V_TN1TC_TIMES_IN-DAYS_EXT .
TN1TC_TIMES_INST-DAYS_APPL =
V_TN1TC_TIMES_IN-DAYS_APPL .
TN1TC_TIMES_INST-ERDAT =
V_TN1TC_TIMES_IN-ERDAT .
TN1TC_TIMES_INST-ERUSR =
V_TN1TC_TIMES_IN-ERUSR .
TN1TC_TIMES_INST-UPDAT =
V_TN1TC_TIMES_IN-UPDAT .
TN1TC_TIMES_INST-UPUSR =
V_TN1TC_TIMES_IN-UPUSR .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_TIMES_INST ##WARN_OK.
    ELSE.
    INSERT TN1TC_TIMES_INST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_TN1TC_TIMES_IN-UPD_FLAG,
STATUS_V_TN1TC_TIMES_IN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_TN1TC_TIMES_IN.
  SELECT SINGLE * FROM TN1TC_TIMES_INST WHERE
INSTITUTION_ID = V_TN1TC_TIMES_IN-INSTITUTION_ID AND
OU_RESP = V_TN1TC_TIMES_IN-OU_RESP .
V_TN1TC_TIMES_IN-MANDT =
TN1TC_TIMES_INST-MANDT .
V_TN1TC_TIMES_IN-INSTITUTION_ID =
TN1TC_TIMES_INST-INSTITUTION_ID .
V_TN1TC_TIMES_IN-OU_RESP =
TN1TC_TIMES_INST-OU_RESP .
V_TN1TC_TIMES_IN-DAYS_EXT =
TN1TC_TIMES_INST-DAYS_EXT .
V_TN1TC_TIMES_IN-DAYS_APPL =
TN1TC_TIMES_INST-DAYS_APPL .
V_TN1TC_TIMES_IN-ERDAT =
TN1TC_TIMES_INST-ERDAT .
V_TN1TC_TIMES_IN-ERUSR =
TN1TC_TIMES_INST-ERUSR .
V_TN1TC_TIMES_IN-UPDAT =
TN1TC_TIMES_INST-UPDAT .
V_TN1TC_TIMES_IN-UPUSR =
TN1TC_TIMES_INST-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_TIMES_INST-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_IN-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_IN-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_TIMES_INST-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_IN-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_TIMES_IN-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_IN-OU_RESP_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_TN1TC_TIMES_IN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_TN1TC_TIMES_IN-INSTITUTION_ID TO
TN1TC_TIMES_INST-INSTITUTION_ID .
MOVE V_TN1TC_TIMES_IN-OU_RESP TO
TN1TC_TIMES_INST-OU_RESP .
MOVE V_TN1TC_TIMES_IN-MANDT TO
TN1TC_TIMES_INST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_TIMES_INST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_TIMES_INST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_TIMES_INST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_V_TN1TC_TIMES_IN USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
TN1TC_TIMES_INST-MANDT =
V_TN1TC_TIMES_IN-MANDT .
TN1TC_TIMES_INST-INSTITUTION_ID =
V_TN1TC_TIMES_IN-INSTITUTION_ID .
TN1TC_TIMES_INST-OU_RESP =
V_TN1TC_TIMES_IN-OU_RESP .
TN1TC_TIMES_INST-DAYS_EXT =
V_TN1TC_TIMES_IN-DAYS_EXT .
TN1TC_TIMES_INST-DAYS_APPL =
V_TN1TC_TIMES_IN-DAYS_APPL .
TN1TC_TIMES_INST-ERDAT =
V_TN1TC_TIMES_IN-ERDAT .
TN1TC_TIMES_INST-ERUSR =
V_TN1TC_TIMES_IN-ERUSR .
TN1TC_TIMES_INST-UPDAT =
V_TN1TC_TIMES_IN-UPDAT .
TN1TC_TIMES_INST-UPUSR =
V_TN1TC_TIMES_IN-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_TIMES_INST-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_IN-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_IN-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_TIMES_INST-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_IN-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_TIMES_IN-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_IN-OU_RESP_TEXT .
    ENDIF.
ENDFORM.
*...processing: V_TN1TC_TIMES_OU................................*
FORM GET_DATA_V_TN1TC_TIMES_OU.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM TN1TC_TIMES_OU WHERE
(VIM_WHERETAB) .
    CLEAR V_TN1TC_TIMES_OU .
V_TN1TC_TIMES_OU-MANDT =
TN1TC_TIMES_OU-MANDT .
V_TN1TC_TIMES_OU-INSTITUTION_ID =
TN1TC_TIMES_OU-INSTITUTION_ID .
V_TN1TC_TIMES_OU-OU_RESP =
TN1TC_TIMES_OU-OU_RESP .
V_TN1TC_TIMES_OU-DEPTOU =
TN1TC_TIMES_OU-DEPTOU .
V_TN1TC_TIMES_OU-TREAOU =
TN1TC_TIMES_OU-TREAOU .
V_TN1TC_TIMES_OU-DAYS_EXT =
TN1TC_TIMES_OU-DAYS_EXT .
V_TN1TC_TIMES_OU-DAYS_APPL =
TN1TC_TIMES_OU-DAYS_APPL .
V_TN1TC_TIMES_OU-ERDAT =
TN1TC_TIMES_OU-ERDAT .
V_TN1TC_TIMES_OU-ERUSR =
TN1TC_TIMES_OU-ERUSR .
V_TN1TC_TIMES_OU-UPDAT =
TN1TC_TIMES_OU-UPDAT .
V_TN1TC_TIMES_OU-UPUSR =
TN1TC_TIMES_OU-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_TIMES_OU-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-EINKB =
TN01-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_TIMES_OU-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM NORG WHERE
ORGID = TN1TC_TIMES_OU-DEPTOU .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-DEPTOU_KB =
NORG-ORGKB .
V_TN1TC_TIMES_OU-TREAOU_KB =
NORG-ORGKB .
    ENDIF.
<VIM_TOTAL_STRUC> = V_TN1TC_TIMES_OU.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_V_TN1TC_TIMES_OU .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO V_TN1TC_TIMES_OU.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_V_TN1TC_TIMES_OU-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_TIMES_OU WHERE
  INSTITUTION_ID = V_TN1TC_TIMES_OU-INSTITUTION_ID AND
  OU_RESP = V_TN1TC_TIMES_OU-OU_RESP AND
  DEPTOU = V_TN1TC_TIMES_OU-DEPTOU AND
  TREAOU = V_TN1TC_TIMES_OU-TREAOU .
    IF SY-SUBRC = 0.
    DELETE TN1TC_TIMES_OU .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM TN1TC_TIMES_OU WHERE
  INSTITUTION_ID = V_TN1TC_TIMES_OU-INSTITUTION_ID AND
  OU_RESP = V_TN1TC_TIMES_OU-OU_RESP AND
  DEPTOU = V_TN1TC_TIMES_OU-DEPTOU AND
  TREAOU = V_TN1TC_TIMES_OU-TREAOU .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR TN1TC_TIMES_OU.
    ENDIF.
TN1TC_TIMES_OU-MANDT =
V_TN1TC_TIMES_OU-MANDT .
TN1TC_TIMES_OU-INSTITUTION_ID =
V_TN1TC_TIMES_OU-INSTITUTION_ID .
TN1TC_TIMES_OU-OU_RESP =
V_TN1TC_TIMES_OU-OU_RESP .
TN1TC_TIMES_OU-DEPTOU =
V_TN1TC_TIMES_OU-DEPTOU .
TN1TC_TIMES_OU-TREAOU =
V_TN1TC_TIMES_OU-TREAOU .
TN1TC_TIMES_OU-DAYS_EXT =
V_TN1TC_TIMES_OU-DAYS_EXT .
TN1TC_TIMES_OU-DAYS_APPL =
V_TN1TC_TIMES_OU-DAYS_APPL .
TN1TC_TIMES_OU-ERDAT =
V_TN1TC_TIMES_OU-ERDAT .
TN1TC_TIMES_OU-ERUSR =
V_TN1TC_TIMES_OU-ERUSR .
TN1TC_TIMES_OU-UPDAT =
V_TN1TC_TIMES_OU-UPDAT .
TN1TC_TIMES_OU-UPUSR =
V_TN1TC_TIMES_OU-UPUSR .
    IF SY-SUBRC = 0.
    UPDATE TN1TC_TIMES_OU ##WARN_OK.
    ELSE.
    INSERT TN1TC_TIMES_OU .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_V_TN1TC_TIMES_OU-UPD_FLAG,
STATUS_V_TN1TC_TIMES_OU-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_V_TN1TC_TIMES_OU.
  SELECT SINGLE * FROM TN1TC_TIMES_OU WHERE
INSTITUTION_ID = V_TN1TC_TIMES_OU-INSTITUTION_ID AND
OU_RESP = V_TN1TC_TIMES_OU-OU_RESP AND
DEPTOU = V_TN1TC_TIMES_OU-DEPTOU AND
TREAOU = V_TN1TC_TIMES_OU-TREAOU .
V_TN1TC_TIMES_OU-MANDT =
TN1TC_TIMES_OU-MANDT .
V_TN1TC_TIMES_OU-INSTITUTION_ID =
TN1TC_TIMES_OU-INSTITUTION_ID .
V_TN1TC_TIMES_OU-OU_RESP =
TN1TC_TIMES_OU-OU_RESP .
V_TN1TC_TIMES_OU-DEPTOU =
TN1TC_TIMES_OU-DEPTOU .
V_TN1TC_TIMES_OU-TREAOU =
TN1TC_TIMES_OU-TREAOU .
V_TN1TC_TIMES_OU-DAYS_EXT =
TN1TC_TIMES_OU-DAYS_EXT .
V_TN1TC_TIMES_OU-DAYS_APPL =
TN1TC_TIMES_OU-DAYS_APPL .
V_TN1TC_TIMES_OU-ERDAT =
TN1TC_TIMES_OU-ERDAT .
V_TN1TC_TIMES_OU-ERUSR =
TN1TC_TIMES_OU-ERUSR .
V_TN1TC_TIMES_OU-UPDAT =
TN1TC_TIMES_OU-UPDAT .
V_TN1TC_TIMES_OU-UPUSR =
TN1TC_TIMES_OU-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_TIMES_OU-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_OU-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_TIMES_OU-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_TIMES_OU-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_OU-OU_RESP_TEXT .
    ENDIF.
    SELECT SINGLE * FROM NORG WHERE
ORGID = TN1TC_TIMES_OU-DEPTOU .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-DEPTOU_KB =
NORG-ORGKB .
V_TN1TC_TIMES_OU-TREAOU_KB =
NORG-ORGKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_OU-DEPTOU_KB .
      CLEAR V_TN1TC_TIMES_OU-TREAOU_KB .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_V_TN1TC_TIMES_OU USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE V_TN1TC_TIMES_OU-INSTITUTION_ID TO
TN1TC_TIMES_OU-INSTITUTION_ID .
MOVE V_TN1TC_TIMES_OU-OU_RESP TO
TN1TC_TIMES_OU-OU_RESP .
MOVE V_TN1TC_TIMES_OU-DEPTOU TO
TN1TC_TIMES_OU-DEPTOU .
MOVE V_TN1TC_TIMES_OU-TREAOU TO
TN1TC_TIMES_OU-TREAOU .
MOVE V_TN1TC_TIMES_OU-MANDT TO
TN1TC_TIMES_OU-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'TN1TC_TIMES_OU'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN TN1TC_TIMES_OU TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'TN1TC_TIMES_OU'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_V_TN1TC_TIMES_OU USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
TN1TC_TIMES_OU-MANDT =
V_TN1TC_TIMES_OU-MANDT .
TN1TC_TIMES_OU-INSTITUTION_ID =
V_TN1TC_TIMES_OU-INSTITUTION_ID .
TN1TC_TIMES_OU-OU_RESP =
V_TN1TC_TIMES_OU-OU_RESP .
TN1TC_TIMES_OU-DEPTOU =
V_TN1TC_TIMES_OU-DEPTOU .
TN1TC_TIMES_OU-TREAOU =
V_TN1TC_TIMES_OU-TREAOU .
TN1TC_TIMES_OU-DAYS_EXT =
V_TN1TC_TIMES_OU-DAYS_EXT .
TN1TC_TIMES_OU-DAYS_APPL =
V_TN1TC_TIMES_OU-DAYS_APPL .
TN1TC_TIMES_OU-ERDAT =
V_TN1TC_TIMES_OU-ERDAT .
TN1TC_TIMES_OU-ERUSR =
V_TN1TC_TIMES_OU-ERUSR .
TN1TC_TIMES_OU-UPDAT =
V_TN1TC_TIMES_OU-UPDAT .
TN1TC_TIMES_OU-UPUSR =
V_TN1TC_TIMES_OU-UPUSR .
    SELECT SINGLE * FROM TN01 WHERE
EINRI = TN1TC_TIMES_OU-INSTITUTION_ID .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-EINKB =
TN01-EINKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_OU-EINKB .
    ENDIF.
    SELECT SINGLE * FROM TN1TC_OU_RESP WHERE
OU_RESP = TN1TC_TIMES_OU-OU_RESP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TN1TC_OU_RESPT WHERE
OU_RESP = TN1TC_OU_RESP-OU_RESP AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-OU_RESP_TEXT =
TN1TC_OU_RESPT-OU_RESP_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR V_TN1TC_TIMES_OU-OU_RESP_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_OU-OU_RESP_TEXT .
    ENDIF.
    SELECT SINGLE * FROM NORG WHERE
ORGID = TN1TC_TIMES_OU-DEPTOU .
    IF SY-SUBRC EQ 0.
V_TN1TC_TIMES_OU-DEPTOU_KB =
NORG-ORGKB .
V_TN1TC_TIMES_OU-TREAOU_KB =
NORG-ORGKB .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR V_TN1TC_TIMES_OU-DEPTOU_KB .
      CLEAR V_TN1TC_TIMES_OU-TREAOU_KB .
    ENDIF.
ENDFORM.
