*"* components of interface IF_ISH_GRAFIK_CONSTANTS
interface IF_ISH_GRAFIK_CONSTANTS
  public .


  constants SGRC_CONST_STAT_1 type NET_GRAPH-STAT value '1'. "#EC NOTEXT
  constants SGRC_CONST_STAT_2 type NET_GRAPH-STAT value '2'. "#EC NOTEXT
  constants SGRC_CONST_STAT_3 type NET_GRAPH-STAT value '3'. "#EC NOTEXT
  constants SGRC_CONST_STAT_4 type NET_GRAPH-STAT value '4'. "#EC NOTEXT
  constants SGRC_CONST_STAT_5 type NET_GRAPH-STAT value '5'. "#EC NOTEXT
  constants SGRC_CONST_STAT_6 type NET_GRAPH-STAT value '6'. "#EC NOTEXT
  constants SGRC_CONST_STAT_7 type NET_GRAPH-STAT value '7'. "#EC NOTEXT
  constants SGRC_CONST_STAT_REUSE type NET_GRAPH-STAT value 'R'. "#EC NOTEXT
  constants SGRC_CONST_M_TYP_D type NET_GRAPH-M_TYP value 'D'. "#EC NOTEXT
  constants SGRC_CONST_M_TYP_I type NET_GRAPH-M_TYP value 'I'. "#EC NOTEXT
  constants SGRC_CONST_M_TYP_Q type NET_GRAPH-M_TYP value 'Q'. "#EC NOTEXT
  constants SGRC_CONST_M_TYP_E type NET_GRAPH-M_TYP value 'E'. "#EC NOTEXT
  constants SGRC_CONST_M_TYP_0 type NET_GRAPH-M_TYP value '0'. "#EC NOTEXT
  constants SGRC_CONST_M_TYP_SPACE type NET_GRAPH-M_TYP value ' '. "#EC NOTEXT
  constants SGRC_CONST_YES type C value '1'. "#EC NOTEXT
  constants SGRC_CONST_NO type C value '0'. "#EC NOTEXT
  constants SGRC_CONST_TRUE type C value '1'. "#EC NOTEXT
  constants SGRC_CONST_FALSE type C value '0'. "#EC NOTEXT
  constants SGRC_CONST_MARKED type C value 'X'. "#EC NOTEXT
  constants SGRC_CONST_BLACK type THLT-BG_COL value 'BLACK'. "#EC NOTEXT
  constants SGRC_CONST_BLUE type THLT-BG_COL value 'BLUE'. "#EC NOTEXT
  constants SGRC_CONST_CYAN type THLT-BG_COL value 'CYAN'. "#EC NOTEXT
  constants SGRC_CONST_DARKBLUE type THLT-BG_COL value 'DARKBLUE'. "#EC NOTEXT
  constants SGRC_CONST_DARKCYAN type THLT-BG_COL value 'DARKCYAN'. "#EC NOTEXT
  constants SGRC_CONST_DARKGRAY type THLT-BG_COL value 'DARKGRAY'. "#EC NOTEXT
  constants SGRC_CONST_DARKGREEN type THLT-BG_COL value 'DARKGREEN'. "#EC NOTEXT
  constants SGRC_CONST_DARKMAGENTA type THLT-BG_COL value 'DARKMAGENTA'. "#EC NOTEXT
  constants SGRC_CONST_DARKRED type THLT-BG_COL value 'DARKRED'. "#EC NOTEXT
  constants SGRC_CONST_DARKYELLOW type THLT-BG_COL value 'DARKYELLOW'. "#EC NOTEXT
  constants SGRC_CONST_GRAY type THLT-BG_COL value 'GRAY'. "#EC NOTEXT
  constants SGRC_CONST_GREEN type THLT-BG_COL value 'GREEN'. "#EC NOTEXT
  constants SGRC_CONST_MAGENTA type THLT-BG_COL value 'MAGENTA'. "#EC NOTEXT
  constants SGRC_CONST_RED type THLT-BG_COL value 'RED'. "#EC NOTEXT
  constants SGRC_CONST_WHITE type THLT-BG_COL value 'WHITE'. "#EC NOTEXT
  constants SGRC_CONST_YELLOW type THLT-BG_COL value 'YELLOW'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_B type C value 'B'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_C type C value 'C'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_D type C value 'D'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_G type C value 'G'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_I type C value 'I'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_K type C value 'K'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_N type C value 'N'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_O type C value 'O'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_S type C value 'S'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_T type C value 'T'. "#EC NOTEXT
  constants SGRC_CONST_MSG_IDENT_Z type C value 'Z'. "#EC NOTEXT
  constants SGRC_CONST_END_MESSAGE type CHAR3 value 'END'. "#EC NOTEXT
  constants SGRC_CONST_MAIN_DYNNR type CHAR4 value '2002'. "#EC NOTEXT
  constants SGRC_CONST_MAIN_REPID type CHAR8 value 'SAPLSGRC'. "#EC NOTEXT
  constants SGRC_CONST_EVENT type CHAR4 value '%_GC'. "#EC NOTEXT
  constants SGRC_CONST_SHELL_EVENT type CHAR4 value '%_GS'. "#EC NOTEXT
  constants BC_CONST_CHART_BORDER_BOX type BCVALS-FL value 'b'. "#EC NOTEXT
  constants BC_CONST_CHART_CENTER_TO_BOX type BCVALS-FL value 'c'. "#EC NOTEXT
  constants BC_CONST_CHART_EMPTY_ROWS type BCVALS-FL value 'r'. "#EC NOTEXT
  constants BC_CONST_CHART_VERTICAL_SIZE type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_CHART_TITLE_BOX type BCVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_TABLETITLE_COLOR type BCVALS-FL value '1'. "#EC NOTEXT
  constants BC_CONST_TIMESCALE_COLOR type BCVALS-FL value '2'. "#EC NOTEXT
  constants BC_CONST_TABLESECTION_COLOR type BCVALS-FL value '3'. "#EC NOTEXT
  constants BC_CONST_DIAGRAMSECTION_COLOR type BCVALS-FL value '4'. "#EC NOTEXT
  constants BC_CONST_DEFAULT_BOX_FORM type BCVALS-FL value 'f'. "#EC NOTEXT
  constants BC_CONST_DEFAULT_NODE_FORM type BCVALS-FL value 'n'. "#EC NOTEXT
  constants BC_CONST_DEFAULT_LINK_MARKCOL type BCVALS-FL value 'l'. "#EC NOTEXT
  constants BC_CONST_DEFAULT_INS_COLOR type BCVALS-FL value 'h'. "#EC NOTEXT
  constants BC_CONST_FORMFIELD_FOR_SELECT type BCVALS-FL value 'D'. "#EC NOTEXT
  constants BC_CONST_TEXT_FOR_SELECT type BCVALS-FL value 'E'. "#EC NOTEXT
  constants BC_CONST_TEXT_FOR_UNSELECT type BCVALS-FL value 'K'. "#EC NOTEXT
  constants BC_CONST_COLOR_FOR_SELECT type BCVALS-FL value 'M'. "#EC NOTEXT
  constants BC_CONST_DEFAULT_HEIGHT type BCVALS-FL value 'w'. "#EC NOTEXT
  constants BC_CONST_MULTI_LINE_CONFIRM type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_OVERLAP_LAYER type BCVALS-FL value 'u'. "#EC NOTEXT
  constants BC_CONST_BORDER_BOX type BCVALS-FL value 'B'. "#EC NOTEXT
  constants BC_CONST_ROW_BOX type BCVALS-FL value 'R'. "#EC NOTEXT
  constants BC_CONST_COLUMN_BOX type BCVALS-FL value 'C'. "#EC NOTEXT
  constants BC_CONST_SELECTED_BOX type BCVALS-FL value 'S'. "#EC NOTEXT
  constants BC_CONST_LINE_COLOR type BCVALS-FL value 'L'. "#EC NOTEXT
  constants BC_CONST_FORM_TYPE type BCVALS-FL value 'F'. "#EC NOTEXT
  constants BC_CONST_BACKGROUND_COLOR type BCVALS-FL value 'B'. "#EC NOTEXT
  constants BC_CONST_FIELD_COLOR type BCVALS-FL value 'C'. "#EC NOTEXT
  constants BC_CONST_DATE type BCVALS-FL value 'd'. "#EC NOTEXT
  constants BC_CONST_COLOR_TYPE type BCVALS-FL value 'h'. "#EC NOTEXT
  constants BC_CONST_LINK_FORMAT type C value 'N'. "#EC NOTEXT
  constants BC_CONST_BOX_FORMAT type C value 'B'. "#EC NOTEXT
  constants BC_CONST_TABLEBOX_FORMAT type C value 'T'. "#EC NOTEXT
  constants BC_CONST_LAYER_FORMAT type C value 'L'. "#EC NOTEXT
  constants BC_CONST_RIBBON_FORMAT type C value 'R'. "#EC NOTEXT
  constants BC_CONST_LINE_GRID type BCGRIDS-TYPE value 'L'. "#EC NOTEXT
  constants BC_CONST_GLOBAL_LINE_GRID type BCGRIDS-TYPE value 'D'. "#EC NOTEXT
  constants BC_CONST_CALENDAR_GRID type BCGRIDS-TYPE value 'C'. "#EC NOTEXT
  constants BC_CONST_GLOBAL_CALENDAR_GRID type BCGRIDS-TYPE value 'M'. "#EC NOTEXT
  constants BC_CONST_SHIFT_GRID type BCGRIDS-TYPE value 'S'. "#EC NOTEXT
  constants BC_CONST_GLOBAL_SHIFT_GRID type BCGRIDS-TYPE value 'N'. "#EC NOTEXT
  constants BC_CONST_HORIZONTAL_GRID type BCGRIDS-TYPE value 'R'. "#EC NOTEXT
  constants BC_CONST_VERTICAL_TIMEAX_GRID type BCGRIDS-TYPE value 'B'. "#EC NOTEXT
  constants BC_CONST_GLOBAL_VERTICAL_TIME type BCGRIDS-TYPE value 'A'. "#EC NOTEXT
  constants BC_CONST_CALENDAR type BCVALS-FL value 'c'. "#EC NOTEXT
  constants BC_CONST_PERIOD type BCVALS-FL value 'p'. "#EC NOTEXT
  constants BC_CONST_SECTION type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_GRID_TIME_UNIT type BCVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_POSITION_BEGIN type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_POSITION_END type BCVALS-FL value 'e'. "#EC NOTEXT
  constants BC_CONST_GRID_PRIORITY type BCVALS-FL value 'r'. "#EC NOTEXT
  constants BC_CONST_GRID_OFFSET type BCVALS-FL value 'd'. "#EC NOTEXT
  constants BC_CONST_ADD_SCOPE type BCVALS-FL value 'b'. "#EC NOTEXT
  constants BC_CONST_REMOVE_SCOPE type BCVALS-FL value 'f'. "#EC NOTEXT
  constants BC_CONST_DEL_COMP_SCOPE type BCVALS-FL value 'x'. "#EC NOTEXT
  constants BC_CONST_VISIBILITY type BCVALS-FL value 'v'. "#EC NOTEXT
  constants BC_CONST_ADD_LINE type BCVALS-FL value 'A'. "#EC NOTEXT
  constants BC_CONST_REMOVE_LINE type BCVALS-FL value 'R'. "#EC NOTEXT
  constants BC_CONST_INTERVAL_START type BCVALS-FL value 'S'. "#EC NOTEXT
  constants BC_CONST_INTERVAL_END type BCVALS-FL value 'E'. "#EC NOTEXT
  constants BC_CONST_MOD_FACTOR type BCVALS-FL value 'Z'. "#EC NOTEXT
  constants BC_CONST_TEXT_INDEX type BCVALS-FL value 'T'. "#EC NOTEXT
  constants BC_CONST_VALIDITY type BCVALS-FL value 'V'. "#EC NOTEXT
  constants BC_CONST_NW_INTERVAL type BCVALS-FL value '1'. "#EC NOTEXT
  constants BC_CONST_WORK_INTERVAL type BCVALS-FL value '2'. "#EC NOTEXT
  constants BC_CONST_WORK_AND_NW_INTV type BCVALS-FL value '3'. "#EC NOTEXT
  constants BC_CONST_MERGE_WORKTIME type BCCALENDAR-TYPE value 'W'. "#EC NOTEXT
  constants BC_CONST_MERGE_NONWORKTIME type BCCALENDAR-TYPE value 'N'. "#EC NOTEXT
  constants BC_CONST_ADD_PROFILE type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_REMOVE_PROFILE type BCVALS-FL value 'r'. "#EC NOTEXT
  constants BC_CONST_UNIQUE_INTERVAL type BCVALS-FL value 'u'. "#EC NOTEXT
  constants BC_CONST_UNIQUE_WORK_INTERVAL type BCVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_ADD_START type BCVALS-FL value 'x'. "#EC NOTEXT
  constants BC_CONST_ADD_END_NONWORKTIME type BCVALS-FL value 'y'. "#EC NOTEXT
  constants BC_CONST_ADD_END_WORKTIME type BCVALS-FL value 'z'. "#EC NOTEXT
  constants BC_CONST_ADD_PROFILE_XYZ type BCVALS-FL value 'w'. "#EC NOTEXT
  constants BC_CONST_ADD_TO_MCAL type BCVALS-FL value 'd'. "#EC NOTEXT
  constants BC_CONST_REMOVE_FROM_MCAL type BCVALS-FL value 'e'. "#EC NOTEXT
  constants BC_CONST_LINK_PRIORITY type BCNVALS-FL value 'L'. "#EC NOTEXT
  constants BC_CONST_LINK_PREDECESSOR type BCNVALS-FL value 'P'. "#EC NOTEXT
  constants BC_CONST_LINK_SUCCESSOR type BCNVALS-FL value 'S'. "#EC NOTEXT
  constants BC_CONST_LINK_VISIBILITY type BCNVALS-FL value 'V'. "#EC NOTEXT
  constants BC_CONST_INK_PORT type BCNVALS-FL value 'Y'. "#EC NOTEXT
  constants BC_CONST_LINK_TYPE type BCNVALS-FL value 'T'. "#EC NOTEXT
  constants BC_CONST_LINK_AOB_AA type BCLINKS-AOB value 'AA'. "#EC NOTEXT
  constants BC_CONST_LINK_AOB_AE type BCLINKS-AOB value 'AE'. "#EC NOTEXT
  constants BC_CONST_LINK_AOB_EA type BCLINKS-AOB value 'EA'. "#EC NOTEXT
  constants BC_CONST_LINK_AOB_EE type BCLINKS-AOB value 'EE'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_16 type BCNVALS-FL value '16'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_17 type BCNVALS-FL value '17'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_18 type BCNVALS-FL value '18'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_19 type BCNVALS-FL value '19'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_20 type BCNVALS-FL value '20'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_21 type BCNVALS-FL value '21'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_22 type BCNVALS-FL value '22'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_23 type BCNVALS-FL value '23'. "#EC NOTEXT
  constants BC_CONST_LINK_PORT_24 type BCNVALS-FL value '24'. "#EC NOTEXT
  constants BC_CONST_LINK_BEGIN type BCNVALS-FL value 'b'. "#EC NOTEXT
  constants BC_CONST_LINK_END type BCNVALS-FL value 'e'. "#EC NOTEXT
  constants BC_CONST_START_LAYER type BCNVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_END_LAYER type BCNVALS-FL value 'z'. "#EC NOTEXT
  constants BC_CONST_MARK_LINK type BCNVALS-FL value 'm'. "#EC NOTEXT
  constants BC_CONST_ADD_LAYER type BCNVALS-FL value 'A'. "#EC NOTEXT
  constants BC_CONST_REMOVE_LAYER type BCNVALS-FL value 'R'. "#EC NOTEXT
  constants BC_CONST_SET_CALENDAR type BCNVALS-FL value 'C'. "#EC NOTEXT
  constants BC_CONST_REMOVE_CALENDAR type BCNVALS-FL value 'D'. "#EC NOTEXT
  constants BC_CONST_SELECTED_NODE type BCNVALS-FL value 'S'. "#EC NOTEXT
  constants BC_CONST_ADD_MAKRO type BCNVALS-FL value 'M'. "#EC NOTEXT
  constants BC_CONST_NODE_PRIORITY type BCNVALS-FL value 'P'. "#EC NOTEXT
  constants BC_CONST_GROUP type BCNVALS-FL value '&'. "#EC NOTEXT
  constants BC_CONST_ASSIGN_LAYER type BCNVALS-FL value 'z'. "#EC NOTEXT
  constants BC_CONST_ADD_NODE type BCNVALS-FL value 'o'. "#EC NOTEXT
  constants BC_CONST_REMOVE_NODE type BCNVALS-FL value 'q'. "#EC NOTEXT
  constants BC_CONST_ADD_SUMMARY_NODE type BCNVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_REMOVE_SUMMARY_NODE type BCNVALS-FL value 'u'. "#EC NOTEXT
  constants BC_CONST_LINE_CURVE type BCCURVE-CURVE_TYPE value 'l'. "#EC NOTEXT
  constants BC_CONST_CAPACITY_CURVE type BCCURVE-CURVE_TYPE value 'c'. "#EC NOTEXT
  constants BC_CONST_STEP_CURVE type BCCURVE-CURVE_TYPE value 's'. "#EC NOTEXT
  constants BC_CONST_CURVE_PRIORITY type BCVALS-FL value 'p'. "#EC NOTEXT
  constants BC_CONST_FILL type BCVALS-FL value 'f'. "#EC NOTEXT
  constants BC_CONST_FILL_DELTA type BCVALS-FL value 'd'. "#EC NOTEXT
  constants BC_CONST_ADD_CURVE type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_ADD_SECTION type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_REMOVE_SECTION type BCVALS-FL value 'r'. "#EC NOTEXT
  constants BC_CONST_SET_RIBBON_SECTION type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_SET_COLUMN type BCVALS-FL value 'SC'. "#EC NOTEXT
  constants BC_CONST_RECTANGLE_LAYER type BCVALS-FL value 'R'. "#EC NOTEXT
  constants BC_CONST_SYMBOL_LAYER type BCVALS-FL value 'S'. "#EC NOTEXT
  constants BC_CONST_LINE_LAYER type BCVALS-FL value 'L'. "#EC NOTEXT
  constants BC_CONST_LAYER_FIRST_DATE type BCVALS-FL value 'f'. "#EC NOTEXT
  constants BC_CONST_LAYER_SECOND_DATE type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_LAYER_TYPE type BCVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_LAYER_HEIGHT type BCVALS-FL value 'h'. "#EC NOTEXT
  constants BC_CONST_LAYER_OFFSET type BCVALS-FL value 'o'. "#EC NOTEXT
  constants BC_CONST_COLOR_FOR_LAYER type BCVALS-FL value 'c'. "#EC NOTEXT
  constants BC_CONST_FORMAT_FOR_LAYER type BCVALS-FL value 'l'. "#EC NOTEXT
  constants BC_CONST_LAYER_PRIORITY type BCVALS-FL value 'p'. "#EC NOTEXT
  constants BC_CONST_LAYER_GAP_TYPE type BCVALS-FL value 'g'. "#EC NOTEXT
  constants BC_CONST_LAYER_GAP_COLOR type BCVALS-FL value 'b'. "#EC NOTEXT
  constants BC_CONST_LAYER_HOR_OFFSET type BCVALS-FL value 'r'. "#EC NOTEXT
  constants BC_CONST_VC_POINTER_DOWN type BCVALS-FL value '1'. "#EC NOTEXT
  constants BC_CONST_VC_TRIANGLE_DOWN type BCVALS-FL value '2'. "#EC NOTEXT
  constants BC_CONST_VC_GREATER_SIGN type BCVALS-FL value '3'. "#EC NOTEXT
  constants BC_CONST_VC_SLIM_TRIANGLE_UP type BCVALS-FL value '4'. "#EC NOTEXT
  constants BC_CONST_VC_TRIANGLE_RIGHT type BCVALS-FL value '5'. "#EC NOTEXT
  constants BC_CONST_VC_TRIANGLE_LEFT type BCVALS-FL value '6'. "#EC NOTEXT
  constants BC_CONST_VC_RHOMB type BCVALS-FL value '7'. "#EC NOTEXT
  constants BC_CONST_VC_DOUBLE_TRIANGLE type BCVALS-FL value '8'. "#EC NOTEXT
  constants BC_CONST_VC_SLIM_TRIANGLE_DOWN type BCVALS-FL value '9'. "#EC NOTEXT
  constants BC_CONST_VC_SQUARE type BCVALS-FL value '10'. "#EC NOTEXT
  constants BC_CONST_VC_CIRCLE type BCVALS-FL value '11'. "#EC NOTEXT
  constants BC_CONST_VC_POINTER_DOWN_IC type BCVALS-FL value '12'. "#EC NOTEXT
  constants BC_CONST_VC_TRIANGLE_DOWN_IC type BCVALS-FL value '13'. "#EC NOTEXT
  constants BC_CONST_VC_GREATER_SIGN_IC type BCVALS-FL value '14'. "#EC NOTEXT
  constants BC_CONST_VC_SLIM_TRIANGLE type BCVALS-FL value '15'. "#EC NOTEXT
  constants BC_CONST_VC_TRIANGLE_RIGHT_IC type BCVALS-FL value '16'. "#EC NOTEXT
  constants BC_CONST_VC_TRIANGLE_LEFT_IC type BCVALS-FL value '17'. "#EC NOTEXT
  constants BC_CONST_VC_RHOMB_IC type BCVALS-FL value '18'. "#EC NOTEXT
  constants BC_CONST_VC_DOUBLE_TRIANGLE_IC type BCVALS-FL value '19'. "#EC NOTEXT
  constants BC_CONST_VC_SLIM_TRIANDOWN type BCVALS-FL value '20'. "#EC NOTEXT
  constants BC_CONST_VC_SQUARE_IC type BCVALS-FL value '21'. "#EC NOTEXT
  constants BC_CONST_LEGEND_HEADER type BCDELETE-OBJ_TYPE value 'h'. "#EC NOTEXT
  constants BC_CONST_LEGEND_TRAILER type BCDELETE-OBJ_TYPE value 'T'. "#EC NOTEXT
  constants BC_CONST_MENU_CLEAR type BCVALS-FL value 'x'. "#EC NOTEXT
  constants BC_CONST_MENU_ADD type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_MENU_REMOVE type BCVALS-FL value 'R'. "#EC NOTEXT
  constants BC_CONST_SET_MENU type BCVALS-FL value '?'. "#EC NOTEXT
  constants BC_CONST_FONT_COLOR type BCVALS-FL value 'c'. "#EC NOTEXT
  constants BC_CONST_SET_CAL_IN_RIBBON type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_UNIT_SEPARATION type BCVALS-FL value 'u'. "#EC NOTEXT
  constants BC_CONST_SET_MAJOR_TICK type BCVALS-FL value 'm'. "#EC NOTEXT
  constants BC_CONST_SET_MINOR_TICK type BCVALS-FL value 'i'. "#EC NOTEXT
  constants BC_CONST_SET_TIME_TEXT type BCVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_TREE_DIM_EFFECT type BCVALS-FL value 'd'. "#EC NOTEXT
  constants BC_CONST_FONT_NAME type BCVALS-FL value 'n'. "#EC NOTEXT
  constants BC_CONST_FONT_TYPE type BCVALS-FL value 'b'. "#EC NOTEXT
  constants BC_CONST_SET_FORMAT type BCVALS-FL value 'RF'. "#EC NOTEXT
  constants BC_CONST_FONT_SIZE type BCVALS-FL value 'w'. "#EC NOTEXT
  constants BC_CONST_FONT_SIZE_IN_INCH type BCVALS-FL value 'wi'. "#EC NOTEXT
  constants BC_CONST_RIBBON_OFFSET type BCVALS-FL value 'z'. "#EC NOTEXT
  constants BC_CONST_UNIT type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_HELVETICA type BCVALS-VAL value 'h'. "#EC NOTEXT
  constants BC_CONST_COURIER type BCVALS-VAL value 'c'. "#EC NOTEXT
  constants BC_CONST_TIMES type BCVALS-VAL value 't'. "#EC NOTEXT
  constants BC_CONST_REGULAR type BCVALS-VAL value '0'. "#EC NOTEXT
  constants BC_CONST_BOLD type BCVALS-VAL value '1'. "#EC NOTEXT
  constants BC_CONST_ITALIC type BCVALS-VAL value '2'. "#EC NOTEXT
  constants BC_CONST_BOLDITALIC type BCVALS-VAL value '3'. "#EC NOTEXT
  constants BC_CONST_NO_TICKS type BCVALS-VAL value '1'. "#EC NOTEXT
  constants BC_CONST_TICKS_ABOVE type BCVALS-VAL value '2'. "#EC NOTEXT
  constants BC_CONST_TICKS_BELOW type BCVALS-VAL value '3'. "#EC NOTEXT
  constants BC_CONST_FULL_LINE type BCVALS-VAL value '4'. "#EC NOTEXT
  constants BC_CONST_VERTICAL_SECTION type BCSECTION-UNIT value '0'. "#EC NOTEXT
  constants BC_CONST_START_TIME type BCVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_SECTION_TIME_UNIT type BCVALS-FL value 'u'. "#EC NOTEXT
  constants BC_CONST_TIME_UNIT_WIDTH type BCVALS-FL value 'w'. "#EC NOTEXT
  constants BC_CONST_ADD_MCAL type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_REMOVE_MCAL type BCVALS-FL value 'r'. "#EC NOTEXT
  constants BC_CONST_PERIOD_WIDTH type BCVALS-FL value 'p'. "#EC NOTEXT
  constants BC_CONST_NUMBER_OF_PERIODS type BCVALS-FL value 'n'. "#EC NOTEXT
  constants BC_CONST_YEAR_UNIT type BCSECTION-UNIT value '1'. "#EC NOTEXT
  constants BC_CONST_QUATER_UNIT type BCSECTION-UNIT value '2'. "#EC NOTEXT
  constants BC_CONST_MONTH_UNIT type BCSECTION-UNIT value '3'. "#EC NOTEXT
  constants BC_CONST_WEEK_UNIT type BCSECTION-UNIT value '4'. "#EC NOTEXT
  constants BC_CONST_DAY_UNIT type BCSECTION-UNIT value '5'. "#EC NOTEXT
  constants BC_CONST_HOUR_UNIT type BCSECTION-UNIT value '6'. "#EC NOTEXT
  constants BC_CONST_MINUTE_UNIT type BCSECTION-UNIT value '7'. "#EC NOTEXT
  constants BC_CONST_SECOND_UNIT type BCSECTION-UNIT value '8'. "#EC NOTEXT
  constants BC_CONST_SHIFT_UNIT type BCSECTION-UNIT value '12'. "#EC NOTEXT
  constants BC_CONST_VERTICAL_RIBBON type BCRIBBON-UNIT value '138'. "#EC NOTEXT
  constants BC_CONST_CALENDAR_UNIT type BCRIBBON-UNIT value '139'. "#EC NOTEXT
  constants BC_CONST_CURVE_RIBBON type BCRIBBON-UNIT value '152'. "#EC NOTEXT
  constants BC_CONST_MODIFY type BCVALS-FL value 'm'. "#EC NOTEXT
  constants BC_CONST_ENLARGED type BCVALS-FL value 'E'. "#EC NOTEXT
  constants BC_CONST_SELECTED type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_SET_CHART_COLOR type BCVALS-FL value 'cc'. "#EC NOTEXT
  constants BC_CONST_ROW_WIDTH type BCVALS-FL value 'w'. "#EC NOTEXT
  constants BC_CONST_UNIQUE type BCTIMEOBJ-TYPE value 'U'. "#EC NOTEXT
  constants BC_CONST_RECURRENT type BCTIMEOBJ-TYPE value 'R'. "#EC NOTEXT
  constants BC_CONST_DAILY_RECURRENT type BCTIMEOBJ-TYPE value 'D'. "#EC NOTEXT
  constants BC_CONST_DAY_IN_WEEK type BCTIMEOBJ-FL value '0'. "#EC NOTEXT
  constants BC_CONST_WEEK_IN_MONTH type BCTIMEOBJ-FL value '1'. "#EC NOTEXT
  constants BC_CONST_MONDAY type BCTIMEOBJ-TYPE value '1'. "#EC NOTEXT
  constants BC_CONST_TUESDAY type BCTIMEOBJ-TYPE value '2'. "#EC NOTEXT
  constants BC_CONST_WEDNESDAY type BCTIMEOBJ-TYPE value '3'. "#EC NOTEXT
  constants BC_CONST_THURSDAY type BCTIMEOBJ-TYPE value '4'. "#EC NOTEXT
  constants BC_CONST_FRIDAY type BCTIMEOBJ-TYPE value '5'. "#EC NOTEXT
  constants BC_CONST_SATURDAY type BCTIMEOBJ-TYPE value '6'. "#EC NOTEXT
  constants BC_CONST_SUNDAY type BCTIMEOBJ-TYPE value '7'. "#EC NOTEXT
  constants BC_CONST_DAY type BCTIMEPROF-TYPE value 'D'. "#EC NOTEXT
  constants BC_CONST_WEEK type BCTIMEPROF-TYPE value 'W'. "#EC NOTEXT
  constants BC_CONST_YEAR type BCTIMEPROF-TYPE value 'Y'. "#EC NOTEXT
  constants BC_CONST_VARIABLE type BCTIMEPROF-TYPE value 'V'. "#EC NOTEXT
  constants BC_CONST_INTERVAL type BCTIMEPROF-TYPE value 'I'. "#EC NOTEXT
  constants BC_CONST_FULL_PROFILE type BCTIMEPROF-EMPTY_FULL value 'F'. "#EC NOTEXT
  constants BC_CONST_ADD_NW_TIME type BCVALS-FL value 'a'. "#EC NOTEXT
  constants BC_CONST_REMOVE_NW_TIME type BCVALS-FL value 'r'. "#EC NOTEXT
  constants BC_CONST_ADD_NW_INTERVAL type BCVALS-FL value 'b'. "#EC NOTEXT
  constants BC_CONST_REMOVE_NW_INTERVAL type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_EMPTY_PROFILE type BCTIMEPROF-EMPTY_FULL value 'E'. "#EC NOTEXT
  constants BC_CONST_ADD_WORK_TIME type BCVALS-FL value 'C'. "#EC NOTEXT
  constants BC_CONST_REMOVE_WORK_TIME type BCVALS-FL value 't'. "#EC NOTEXT
  constants BC_CONST_ADD_WORK_INTERVAL type BCVALS-FL value 'd'. "#EC NOTEXT
  constants BC_CONST_REMOVE_WORK_INTERVAL type BCVALS-FL value 'u'. "#EC NOTEXT
  constants BC_CONST_ADD_DAY_PROFILE type BCVALS-FL value 'p'. "#EC NOTEXT
  constants BC_CONST_REMOVE_DAY_PROFILE type BCVALS-FL value 'm'. "#EC NOTEXT
  constants BC_CONST_AXIS_OBJECT type C value 'a'. "#EC NOTEXT
  constants BC_CONST_BOX_OBJECT type C value 'B'. "#EC NOTEXT
  constants BC_CONST_CALENDAR_OBJECT type C value 'A'. "#EC NOTEXT
  constants BC_CONST_CHART_OBJECT type C value 'C'. "#EC NOTEXT
  constants BC_CONST_CURVE_OBJECT type C value 'c'. "#EC NOTEXT
  constants BC_CONST_DATELINE_OBJECT type C value 'D'. "#EC NOTEXT
  constants BC_CONST_GRID_OBJECT type C value 'G'. "#EC NOTEXT
  constants BC_CONST_HIGHLIGHT_OBJECT type C value 'H'. "#EC NOTEXT
  constants BC_CONST_LAYER_OBJECT type C value 'L'. "#EC NOTEXT
  constants BC_CONST_LINK_OBJECT type C value 'K'. "#EC NOTEXT
  constants BC_CONST_NODE_OBJECT type C value 'N'. "#EC NOTEXT
  constants BC_CONST_POSITION_OBJECT type C value 'P'. "#EC NOTEXT
  constants BC_CONST_RIBBON_OBJECT type C value 'R'. "#EC NOTEXT
  constants BC_CONST_SECTION_OBJECT type C value 's'. "#EC NOTEXT
  constants BC_CONST_SUMMARY_NODE_OBJECT type C value 'S'. "#EC NOTEXT
  constants BC_CONST_COLUMN_OBJECT type C value 'M'. "#EC NOTEXT
  constants BC_CONST_WIZARD_TEXT type BCVALS-FL value '!'. "#EC NOTEXT
  constants BC_CONST_TITLEBOX type BCCMDINFO-INFO value 'TITLEBOX'. "#EC NOTEXT
  constants BC_CONST_TIMESCALE type BCCMDINFO-INFO value 'TIMESCALE'. "#EC NOTEXT
  constants BC_CONST_TABLETITLE type BCCMDINFO-INFO value 'TABLETITLE'. "#EC NOTEXT
  constants BC_CONST_NODE_MAKR type BCVALS-FL value 'N'. "#EC NOTEXT
  constants BC_CONST_BOX_MAKRO type BCVALS-FL value 'B'. "#EC NOTEXT
  constants BC_CONST_LAYER_MAKRO type BCVALS-FL value 'L'. "#EC NOTEXT
  constants BC_CONST_DEF_ID type NET_GRAPH-WINID value 'BARC'. "#EC NOTEXT
  constants BC_CONST_SELECTED_ROW type BCVALS-FL value 's'. "#EC NOTEXT
  constants BC_CONST_ENLARGED_ROW type BCVALS-FL value 'E'. "#EC NOTEXT
  constants BC_CONST_ON type BCVALS-FL value '1'. "#EC NOTEXT
  constants BC_CONST_OFF type BCVALS-FL value '0'. "#EC NOTEXT
  constants BC_CONST_X type BCVALS-VAL value 'x'. "#EC NOTEXT
  constants BC_CONST_ALIGN type NET_GRAPH-GR_MES value 'ALIGN'. "#EC NOTEXT
  constants BC_CONST_ALIVE type NET_GRAPH-GR_MES value 'ALIVE'. "#EC NOTEXT
  constants BC_CONST_BREAK type NET_GRAPH-GR_MES value 'BREAK'. "#EC NOTEXT
  constants BC_CONST_CUSTOMIZE type NET_GRAPH-GR_MES value 'OBJCUST'. "#EC NOTEXT
  constants BC_CONST_DOUBLE_CLICK type NET_GRAPH-GR_MES value 'DBCL'. "#EC NOTEXT
  constants BC_CONST_EXTENDED_HELP type NET_GRAPH-GR_MES value 'HLP1'. "#EC NOTEXT
  constants BC_CONST_LOCAL_HELP type NET_GRAPH-GR_MES value 'HLP2'. "#EC NOTEXT
  constants BC_CONST_GET_COLOR type NET_GRAPH-GR_MES value 'CLRS'. "#EC NOTEXT
  constants BC_CONST_GET_OVERLAP type NET_GRAPH-GR_MES value 'OVERLAP'. "#EC NOTEXT
  constants BC_CONST_GET_SELECTION type NET_GRAPH-GR_MES value 'SEL'. "#EC NOTEXT
  constants BC_CONST_GET_SETTINGS type NET_GRAPH-GR_MES value 'CUSTOM'. "#EC NOTEXT
  constants BC_CONST_GET_VIEWRANGE type NET_GRAPH-GR_MES value 'VIEWRANGE'. "#EC NOTEXT
  constants BC_CONST_GRANULAT type NET_GRAPH-GR_MES value 'GRANULAT'. "#EC NOTEXT
  constants BC_CONST_HOTSPOT type NET_GRAPH-GR_MES value 'HOTSPOT'. "#EC NOTEXT
  constants BC_CONST_MOVETABCOL type NET_GRAPH-GR_MES value 'AMOVTABCOL'. "#EC NOTEXT
  constants BC_CONST_PARTLOAD type NET_GRAPH-GR_MES value 'PARTLOAD'. "#EC NOTEXT
  constants BC_CONST_PREPARE type NET_GRAPH-GR_MES value 'PREPARE'. "#EC NOTEXT
  constants BC_CONST_PRINT type NET_GRAPH-GR_MES value 'PRINT'. "#EC NOTEXT
  constants BC_CONST_REORG type NET_GRAPH-GR_MES value 'CREORG'. "#EC NOTEXT
  constants BC_CONST_HREORG type NET_GRAPH-GR_MES value 'HREORG'. "#EC NOTEXT
  constants BC_CONST_VREORG type NET_GRAPH-GR_MES value 'VREORG'. "#EC NOTEXT
  constants BC_CONST_SAVE type NET_GRAPH-GR_MES value 'SAVE'. "#EC NOTEXT
  constants BC_CONST_STARTCON type NET_GRAPH-GR_MES value 'STARTCON'. "#EC NOTEXT
  constants BC_CONST_SNDDZIOFAC type NET_GRAPH-GR_MES value 'SNDDZIOFAC'. "#EC NOTEXT
  constants BC_CONST_TIMER type NET_GRAPH-GR_MES value 'U'. "#EC NOTEXT
  constants BC_CONST_VIEWLIMIT type NET_GRAPH-GR_MES value 'VIEWLIMIT'. "#EC NOTEXT
  constants BC_CONST_F1_F4 type NET_GRAPH-GR_MES value 'FCODE'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_BACK type NET_GRAPH-GR_MES value 'ABACK'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_CONNECT type NET_GRAPH-GR_MES value 'ACON'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_CONTINUE type NET_GRAPH-GR_MES value 'WEITER'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_DELETE type NET_GRAPH-GR_MES value 'ADEL'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_DUPLICATE type NET_GRAPH-GR_MES value 'ADUP'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_EXIT type NET_GRAPH-GR_MES value 'AEXIT'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_INSERT type NET_GRAPH-GR_MES value 'AINS'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_MODIFY type NET_GRAPH-GR_MES value 'AMOD'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_MOVEBOX type NET_GRAPH-GR_MES value 'AMOVEBOX'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_MOVECURVE type NET_GRAPH-GR_MES value 'AMOVECURVE'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_MOVELAYER type NET_GRAPH-GR_MES value 'AMOVELAYER'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_MOVEMULTI type NET_GRAPH-GR_MES value 'AMOVEMULTI'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_MOVENODE type NET_GRAPH-GR_MES value 'AMOVENODE'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_QUIT type NET_GRAPH-GR_MES value 'AQUIT'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_SCALELEFT type NET_GRAPH-GR_MES value 'ASCALELEFT'. "#EC NOTEXT
  constants BC_CONST_ASK_FOR_SCALERIGHT type NET_GRAPH-GR_MES value 'ASCALERIGHT'. "#EC NOTEXT
endinterface.
