*"* components of interface IF_ISH_GUI_NODE_MODEL
interface IF_ISH_GUI_NODE_MODEL
  public .


  interfaces IF_ISH_GUI_MODEL .

  constants CO_RELAT_FIRST_CHILD type N1GUI_NODE_RELATIONSHIP value 1. "#EC NOTEXT
  constants CO_RELAT_FIRST_SIBLING type N1GUI_NODE_RELATIONSHIP value 2. "#EC NOTEXT
  constants CO_RELAT_LAST_CHILD type N1GUI_NODE_RELATIONSHIP value 3. "#EC NOTEXT
  constants CO_RELAT_LAST_SIBLING type N1GUI_NODE_RELATIONSHIP value 4. "#EC NOTEXT
  constants CO_RELAT_NEXT_SIBLING type N1GUI_NODE_RELATIONSHIP value 5. "#EC NOTEXT
  constants CO_RELAT_PREV_SIBLING type N1GUI_NODE_RELATIONSHIP value 6. "#EC NOTEXT
endinterface.
