*"* components of interface IF_ISH_GUI_MAIN_CONTROLLER
interface IF_ISH_GUI_MAIN_CONTROLLER
  public .


  interfaces IF_ISH_GUI_CONTROLLER .

  aliases DESTROY
    for IF_ISH_GUI_CONTROLLER~DESTROY .
  aliases GET_APPLICATION
    for IF_ISH_GUI_CONTROLLER~GET_APPLICATION .
  aliases GET_CHILD_CONTROLLERS
    for IF_ISH_GUI_CONTROLLER~GET_CHILD_CONTROLLERS .
  aliases GET_CHILD_CONTROLLER_BY_ID
    for IF_ISH_GUI_CONTROLLER~GET_CHILD_CONTROLLER_BY_ID .
  aliases GET_CHILD_CONTROLLER_BY_NAME
    for IF_ISH_GUI_CONTROLLER~GET_CHILD_CONTROLLER_BY_NAME .
  aliases GET_ELEMENT_ID
    for IF_ISH_GUI_CONTROLLER~GET_ELEMENT_ID .
  aliases GET_ELEMENT_NAME
    for IF_ISH_GUI_CONTROLLER~GET_ELEMENT_NAME .
  aliases GET_MAIN_CONTROLLER
    for IF_ISH_GUI_CONTROLLER~GET_MAIN_CONTROLLER .
  aliases GET_MODEL
    for IF_ISH_GUI_CONTROLLER~GET_MODEL .
  aliases GET_PARENT_CONTROLLER
    for IF_ISH_GUI_CONTROLLER~GET_PARENT_CONTROLLER .
  aliases GET_VCODE
    for IF_ISH_GUI_CONTROLLER~GET_VCODE .
  aliases GET_VIEW
    for IF_ISH_GUI_CONTROLLER~GET_VIEW .
  aliases IS_DESTROYED
    for IF_ISH_GUI_CONTROLLER~IS_DESTROYED .
  aliases IS_INITIALIZED
    for IF_ISH_GUI_CONTROLLER~IS_INITIALIZED .
  aliases IS_IN_DESTROY_MODE
    for IF_ISH_GUI_CONTROLLER~IS_IN_DESTROY_MODE .
  aliases IS_IN_INITIALIZATION_MODE
    for IF_ISH_GUI_CONTROLLER~IS_IN_INITIALIZATION_MODE .
  aliases PROCESS_REQUEST
    for IF_ISH_GUI_CONTROLLER~PROCESS_REQUEST .
  aliases REGISTER_CHILD_CONTROLLER
    for IF_ISH_GUI_CONTROLLER~REGISTER_CHILD_CONTROLLER .
  aliases SET_VCODE
    for IF_ISH_GUI_CONTROLLER~SET_VCODE .
  aliases EV_AFTER_DESTROY
    for IF_ISH_GUI_CONTROLLER~EV_AFTER_DESTROY .
  aliases EV_BEFORE_DESTROY
    for IF_ISH_GUI_CONTROLLER~EV_BEFORE_DESTROY .

  constants CO_DEF_MAIN_CONTROLLER_NAME type N1GUI_ELEMENT_NAME value 'MAIN_CONTROLLER'. "#EC NOTEXT

  methods GET_MDY_VIEW
    returning
      value(RR_MDY_VIEW) type ref to IF_ISH_GUI_MDY_VIEW .
endinterface.
