*"* components of interface IF_ISH_GUI_CONTROL_VIEW
interface IF_ISH_GUI_CONTROL_VIEW
  public .


  interfaces IF_ISH_GUI_VIEW .

  aliases CO_VCODE_DISPLAY
    for IF_ISH_GUI_VIEW~CO_VCODE_DISPLAY .
  aliases CO_VCODE_INSERT
    for IF_ISH_GUI_VIEW~CO_VCODE_INSERT .
  aliases CO_VCODE_UPDATE
    for IF_ISH_GUI_VIEW~CO_VCODE_UPDATE .
  aliases ACTUALIZE_LAYOUT
    for IF_ISH_GUI_VIEW~ACTUALIZE_LAYOUT .
  aliases DESTROY
    for IF_ISH_GUI_VIEW~DESTROY .
  aliases GET_APPLICATION
    for IF_ISH_GUI_VIEW~GET_APPLICATION .
  aliases GET_CHILD_VIEWS
    for IF_ISH_GUI_VIEW~GET_CHILD_VIEWS .
  aliases GET_CHILD_VIEW_BY_ID
    for IF_ISH_GUI_VIEW~GET_CHILD_VIEW_BY_ID .
  aliases GET_CHILD_VIEW_BY_NAME
    for IF_ISH_GUI_VIEW~GET_CHILD_VIEW_BY_NAME .
  aliases GET_CONTROLLER
    for IF_ISH_GUI_VIEW~GET_CONTROLLER .
  aliases GET_ELEMENT_ID
    for IF_ISH_GUI_VIEW~GET_ELEMENT_ID .
  aliases GET_ELEMENT_NAME
    for IF_ISH_GUI_VIEW~GET_ELEMENT_NAME .
  aliases GET_LAYOUT
    for IF_ISH_GUI_VIEW~GET_LAYOUT .
  aliases GET_PARENT_VIEW
    for IF_ISH_GUI_VIEW~GET_PARENT_VIEW .
  aliases GET_VCODE
    for IF_ISH_GUI_VIEW~GET_VCODE .
  aliases HAS_FOCUS
    for IF_ISH_GUI_VIEW~HAS_FOCUS .
  aliases IS_DESTROYED
    for IF_ISH_GUI_VIEW~IS_DESTROYED .
  aliases IS_FIRST_DISPLAY_DONE
    for IF_ISH_GUI_VIEW~IS_FIRST_DISPLAY_DONE .
  aliases IS_INITIALIZED
    for IF_ISH_GUI_VIEW~IS_INITIALIZED .
  aliases IS_IN_DESTROY_MODE
    for IF_ISH_GUI_VIEW~IS_IN_DESTROY_MODE .
  aliases IS_IN_FIRST_DISPLAY_MODE
    for IF_ISH_GUI_VIEW~IS_IN_FIRST_DISPLAY_MODE .
  aliases IS_IN_INITIALIZATION_MODE
    for IF_ISH_GUI_VIEW~IS_IN_INITIALIZATION_MODE .
  aliases PROCESS_REQUEST
    for IF_ISH_GUI_VIEW~PROCESS_REQUEST .
  aliases REGISTER_CHILD_VIEW
    for IF_ISH_GUI_VIEW~REGISTER_CHILD_VIEW .
  aliases SAVE_LAYOUT
    for IF_ISH_GUI_VIEW~SAVE_LAYOUT .
  aliases SET_FOCUS
    for IF_ISH_GUI_VIEW~SET_FOCUS .
  aliases SET_VCODE
    for IF_ISH_GUI_VIEW~SET_VCODE .
  aliases EV_AFTER_DESTROY
    for IF_ISH_GUI_VIEW~EV_AFTER_DESTROY .
  aliases EV_BEFORE_DESTROY
    for IF_ISH_GUI_VIEW~EV_BEFORE_DESTROY .

  type-pools ABAP .
  events EV_VISIBILITY_CHANGED
    exporting
      value(E_VISIBLE) type ABAP_BOOL .

  methods FIRST_DISPLAY
    importing
      !I_WITH_CHILD_VIEWS type ABAP_BOOL default ABAP_FALSE
    raising
      CX_ISH_STATIC_HANDLER .
  methods GET_CONTROL
    returning
      value(RR_CONTROL) type ref to CL_GUI_CONTROL .
  methods GET_CONTROL_LAYOUT
    returning
      value(RR_CONTROL_LAYOUT) type ref to CL_ISH_GUI_CONTROL_LAYOUT .
  methods GET_VISIBILITY
    returning
      value(R_VISIBLE) type ABAP_BOOL .
  methods REFRESH_DISPLAY
    importing
      !I_FORCE type ABAP_BOOL default ABAP_FALSE
      !I_WITH_CHILD_VIEWS type ABAP_BOOL default ABAP_FALSE
    preferred parameter I_FORCE
    raising
      CX_ISH_STATIC_HANDLER .
  methods SET_VISIBILITY
    importing
      !I_VISIBLE type ABAP_BOOL default ABAP_TRUE
    returning
      value(R_CHANGED) type ABAP_BOOL
    raising
      CX_ISH_STATIC_HANDLER .
endinterface.
