*"* components of interface IF_ISH_GM_COMPARABLE
interface IF_ISH_GM_COMPARABLE
  public .


  interfaces IF_ISH_GUI_STRUCTURE_MODEL .

  aliases GET_FIELD_CONTENT
    for IF_ISH_GUI_STRUCTURE_MODEL~GET_FIELD_CONTENT .
  aliases GET_SUPPORTED_FIELDS
    for IF_ISH_GUI_STRUCTURE_MODEL~GET_SUPPORTED_FIELDS .
  aliases IS_FIELD_SUPPORTED
    for IF_ISH_GUI_STRUCTURE_MODEL~IS_FIELD_SUPPORTED .
  aliases SET_FIELD_CONTENT
    for IF_ISH_GUI_STRUCTURE_MODEL~SET_FIELD_CONTENT .
  aliases EV_CHANGED
    for IF_ISH_GUI_STRUCTURE_MODEL~EV_CHANGED .

  constants CO_COMPRES_EQUAL type N1COMPARERESULT value '0'. "#EC NOTEXT
  constants CO_COMPRES_GREATER type N1COMPARERESULT value '+1'. "#EC NOTEXT
  constants CO_COMPRES_LESS type N1COMPARERESULT value '-1'. "#EC NOTEXT

  methods COMPARE_TO
    importing
      !IR_OTHER_COMPARABLE type ref to IF_ISH_GM_COMPARABLE
      !I_COMPAREFIELD type ISH_FIELDNAME optional
    returning
      value(R_RESULT) type N1COMPARERESULT
    raising
      CX_ISH_STATIC_HANDLER .
endinterface.
