*"* components of interface IF_ISH_GUI_PARENT_NODE_MODEL
interface IF_ISH_GUI_PARENT_NODE_MODEL
  public .


  interfaces IF_ISH_GUI_NODE_MODEL .
  interfaces IF_ISH_GUI_XTABLE_MODEL .

  aliases CO_RELAT_FIRST_CHILD
    for IF_ISH_GUI_NODE_MODEL~CO_RELAT_FIRST_CHILD .
  aliases CO_RELAT_FIRST_SIBLING
    for IF_ISH_GUI_NODE_MODEL~CO_RELAT_FIRST_SIBLING .
  aliases CO_RELAT_LAST_CHILD
    for IF_ISH_GUI_NODE_MODEL~CO_RELAT_LAST_CHILD .
  aliases CO_RELAT_LAST_SIBLING
    for IF_ISH_GUI_NODE_MODEL~CO_RELAT_LAST_SIBLING .
  aliases CO_RELAT_NEXT_SIBLING
    for IF_ISH_GUI_NODE_MODEL~CO_RELAT_NEXT_SIBLING .
  aliases CO_RELAT_PREV_SIBLING
    for IF_ISH_GUI_NODE_MODEL~CO_RELAT_PREV_SIBLING .
  aliases ADD_ENTRY
    for IF_ISH_GUI_TABLE_MODEL~ADD_ENTRY .
  aliases APPEND_ENTRY
    for IF_ISH_GUI_XTABLE_MODEL~APPEND_ENTRY .
  aliases GET_ENTRIES
    for IF_ISH_GUI_TABLE_MODEL~GET_ENTRIES .
  aliases GET_FIRST_ENTRY
    for IF_ISH_GUI_XTABLE_MODEL~GET_FIRST_ENTRY .
  aliases GET_LAST_ENTRY
    for IF_ISH_GUI_XTABLE_MODEL~GET_LAST_ENTRY .
  aliases GET_NEXT_ENTRY
    for IF_ISH_GUI_XTABLE_MODEL~GET_NEXT_ENTRY .
  aliases GET_PREVIOUS_ENTRY
    for IF_ISH_GUI_XTABLE_MODEL~GET_PREVIOUS_ENTRY .
  aliases PREPEND_ENTRY
    for IF_ISH_GUI_XTABLE_MODEL~PREPEND_ENTRY .
  aliases REMOVE_ENTRY
    for IF_ISH_GUI_TABLE_MODEL~REMOVE_ENTRY .
  aliases EV_ENTRY_ADDED
    for IF_ISH_GUI_TABLE_MODEL~EV_ENTRY_ADDED .
  aliases EV_ENTRY_REMOVED
    for IF_ISH_GUI_TABLE_MODEL~EV_ENTRY_REMOVED .

  methods GET_CHILD_NODES
    returning
      value(RT_CHILD_NODE) type ISH_T_GUI_CHILDNODEMDL_OBJH
    raising
      CX_ISH_STATIC_HANDLER .
  methods GET_FIRST_CHILD_NODE
    returning
      value(RR_FIRST_CHILD_NODE) type ref to IF_ISH_GUI_CHILD_NODE_MODEL
    raising
      CX_ISH_STATIC_HANDLER .
  methods GET_LAST_CHILD_NODE
    returning
      value(RR_LAST_CHILD_NODE) type ref to IF_ISH_GUI_CHILD_NODE_MODEL
    raising
      CX_ISH_STATIC_HANDLER .
  methods GET_NEXT_CHILD_NODE
    importing
      !IR_PREVIOUS_CHILD_NODE type ref to IF_ISH_GUI_CHILD_NODE_MODEL
    returning
      value(RR_NEXT_CHILD_NODE) type ref to IF_ISH_GUI_CHILD_NODE_MODEL
    raising
      CX_ISH_STATIC_HANDLER .
  methods GET_PREVIOUS_CHILD_NODE
    importing
      !IR_NEXT_CHILD_NODE type ref to IF_ISH_GUI_CHILD_NODE_MODEL
    returning
      value(RR_PREVIOUS_CHILD_NODE) type ref to IF_ISH_GUI_CHILD_NODE_MODEL
    raising
      CX_ISH_STATIC_HANDLER .
endinterface.
