*"* components of interface IF_ISH_OBJECT_TYPES
interface IF_ISH_OBJECT_TYPES
  public .


  constants CO_TYPE_APPOINTMENT type I value 001. "#EC NOTEXT
  constants CO_TYPE_MED_SERVICE type I value 002. "#EC NOTEXT
  constants CO_TYPE_PROV_PATIENT type I value 003. "#EC NOTEXT
  constants CO_TYPE_ANCHOR_SRV type I value 004. "#EC NOTEXT
  constants CO_TYPE_REQUEST type I value 005. "#EC NOTEXT
  constants CO_TYPE_PREREG type I value 006. "#EC NOTEXT
  constants CO_TYPE_APP_ENVIRONMENT type I value 007. "#EC NOTEXT
  constants CO_TYPE_TRANSPORT_ORDER type I value 008. "#EC NOTEXT
  constants CO_TYPE_PATIENT type I value 009. "#EC NOTEXT
  constants CO_TYPE_CASE type I value 010. "#EC NOTEXT
  constants CO_TYPE_DIAGNOSE type I value 011. "#EC NOTEXT
  constants CO_TYPE_ADDRESS type I value 012. "#EC NOTEXT
  constants CO_TYPE_DRUG type I value 013. "#EC NOTEXT
  constants CO_TYPE_PRESCRIPTION type I value 014. "#EC NOTEXT
  constants CO_TYPE_DRUGEVENT type I value 015. "#EC NOTEXT
  constants CO_TYPE_DRUGEVENT_CONNECTION type I value 016. "#EC NOTEXT
  constants CO_TYPE_MOVEMENT type I value 017. "#EC NOTEXT
  constants CO_TYPE_DOCUMENT type I value 018. "#EC NOTEXT
  constants CO_TYPE_VITPAR type I value 019. "#EC NOTEXT
  constants CO_TYPE_TEAM type I value 020. "#EC NOTEXT
  constants CO_TYPE_CONTEXT type I value 021. "#EC NOTEXT
  constants CO_TYPE_CONTEXT_OBJ type I value 022. "#EC NOTEXT
  constants CO_TYPE_SURGERY type I value 023. "#EC NOTEXT
  constants CO_TYPE_WL_ABSENCE type I value 024. "#EC NOTEXT
  constants CO_TYPE_PROV_INSURANCE_POLICY type I value 025. "#EC NOTEXT
  constants CO_TYPE_PREREG_DIAGNOSIS type I value 026. "#EC NOTEXT
  constants CO_TYPE_PREREG_PROCEDURE type I value 027. "#EC NOTEXT
  constants CO_TYPE_PROCEDURE type I value 028. "#EC NOTEXT
  constants CO_TYPE_DAYREF_PLAN_AUTH type I value 029. "#EC NOTEXT
  constants CO_TYPE_APPOINTMENT_OFFER type I value 030. "#EC NOTEXT
  constants CO_TYPE_OUTPAT_VISIT type I value 031. "#EC NOTEXT
  constants CO_TYPE_INPAT_ADMIS type I value 032. "#EC NOTEXT
  constants CO_TYPE_OUTPAT_VISIT_MED type I value 033. "#EC NOTEXT
  constants CO_TYPE_INPAT_ADMIS_MED type I value 034. "#EC NOTEXT
  constants CO_TYPE_APPOINTMENT_SIMPLE type I value 035. "#EC NOTEXT
  constants CO_TYPE_CYCLE type I value 036. "#EC NOTEXT
  constants CO_TYPE_CYCLEDEF type I value 037. "#EC NOTEXT
  constants CO_TYPE_GUIDELINE type I value 038. "#EC NOTEXT
  constants CO_TYPE_ITEM type I value 039. "#EC NOTEXT
  constants CO_TYPE_CORDTYP type I value 040. "#EC NOTEXT
  constants CO_TYPE_CORDTTR type I value 041. "#EC NOTEXT
  constants CO_TYPE_CORDTTR_MED type I value 042. "#EC NOTEXT
  constants CO_TYPE_CORDTS type I value 043. "#EC NOTEXT
  constants CO_TYPE_LINK type I value 044. "#EC NOTEXT
  constants CO_TYPE_CORDTAV type I value 045. "#EC NOTEXT
  constants CO_TYPE_CORDTAV_OU type I value 046. "#EC NOTEXT
  constants CO_TYPE_CORDTAV_GPA type I value 047. "#EC NOTEXT
  constants CO_TYPE_ESTAT type I value 048. "#EC NOTEXT
  constants CO_TYPE_STSMA type I value 049. "#EC NOTEXT
  constants CO_TYPE_DESEL type I value 050. "#EC NOTEXT
  constants CO_TYPE_COMPDEF type I value 051. "#EC NOTEXT
  constants CO_TYPE_CORDTYPA type I value 052. "#EC NOTEXT
  constants CO_TYPE_APP_CONSTRAINT type I value 053. "#EC NOTEXT
  constants CO_TYPE_FATTR_TYPE type I value 054. "#EC NOTEXT
  constants CO_TYPE_FATTR_VALUE type I value 055. "#EC NOTEXT
  constants CO_TYPE_FATTR type I value 056. "#EC NOTEXT
  constants CO_TYPE_SCRM type I value 057. "#EC NOTEXT
  constants CO_TYPE_CORDTSTA type I value 058. "#EC NOTEXT
  constants CO_TYPE_CORDTYP_MED type I value 059. "#EC NOTEXT
  constants CO_TYPE_CMETHSTA type I value 060. "#EC NOTEXT
  constants CO_TYPE_CORDER type I value 061. "#EC NOTEXT
  constants CO_TYPE_STATUS type I value 062. "#EC NOTEXT
  constants CO_TYPE_DATEOFFER_MODIFY type I value 063. "#EC NOTEXT
  constants CO_TYPE_N1WPLACE_PG type I value 064. "#EC NOTEXT
  constants CO_TYPE_RADIOLOGY type I value 065. "#EC NOTEXT
  constants CO_TYPE_TRANS_ORDER type I value 066. "#EC NOTEXT
  constants CO_TYPE_ME_PRESCRIPTION type I value 067. "#EC NOTEXT
  constants CO_TYPE_ME_ORDER type I value 068. "#EC NOTEXT
  constants CO_TYPE_ME_EVENT type I value 069. "#EC NOTEXT
  constants CO_TYPE_ME_ODRUG type I value 070. "#EC NOTEXT
  constants CO_TYPE_ME_EDRUG type I value 071. "#EC NOTEXT
  constants CO_TYPE_CORDER_MED type I value 072. "#EC NOTEXT
  constants CO_TYPE_GL_PROPERTY type I value 073. "#EC NOTEXT
  constants CO_TYPE_N1WPLACE_PG_USZ type I value 074. "#EC NOTEXT
  constants CO_TYPE_N1WVIEW_PG_OU type I value 075. "#EC NOTEXT
  constants CO_TYPE_N1WVIEW_PG_DT type I value 076. "#EC NOTEXT
  constants CO_TYPE_N1WVIEW_PG_PO type I value 077. "#EC NOTEXT
  constants CO_TYPE_N1WVIEW_PG_DT_OU type I value 078. "#EC NOTEXT
  constants CO_TYPE_N1WVIEW_PG_CL type I value 079. "#EC NOTEXT
  constants CO_TYPE_ME_AGENT type I value 080. "#EC NOTEXT
  constants CO_TYPE_ME_FORMULARY type I value 081. "#EC NOTEXT
  constants CO_TYPE_ME_DC type I value 082. "#EC NOTEXT
  constants CO_TYPE_ME_BDCC type I value 083. "#EC NOTEXT
  constants CO_TYPE_GL_DESCRIPTION type I value 084. "#EC NOTEXT
  constants CO_TYPE_GL_URL type I value 085. "#EC NOTEXT
  constants CO_TYPE_GL_DIAGNOSIS type I value 086. "#EC NOTEXT
  constants CO_TYPE_GL_PROCEDURE type I value 087. "#EC NOTEXT
  constants CO_TYPE_FREE1 type I value 088. "#EC NOTEXT
  constants CO_TYPE_FREE2 type I value 089. "#EC NOTEXT
  constants CO_TYPE_NWPLACE type I value 090. "#EC NOTEXT
  constants CO_TYPE_NWPLACET type I value 091. "#EC NOTEXT
  constants CO_TYPE_NWPLACE_MED type I value 092. "#EC NOTEXT
  constants CO_TYPE_NWPLACET_MED type I value 093. "#EC NOTEXT
  constants CO_TYPE_NWVIEW type I value 094. "#EC NOTEXT
  constants CO_TYPE_NWVIEWT type I value 095. "#EC NOTEXT
  constants CO_TYPE_NWVIEW_MED type I value 096. "#EC NOTEXT
  constants CO_TYPE_NWVIEWT_MED type I value 097. "#EC NOTEXT
  constants CO_TYPE_GL_SVG type I value 098. "#EC NOTEXT
  constants CO_TYPE_ME_ORATE type I value 099. "#EC NOTEXT
  constants CO_TYPE_GL_TM_STEP type I value 100. "#EC NOTEXT
  constants CO_TYPE_GL_TM_SCHEDULE type I value 101. "#EC NOTEXT
  constants CO_TYPE_FREE3 type I value 102. "#EC NOTEXT
  constants CO_TYPE_CORDPOS_MED type I value 103. "#EC NOTEXT
  constants CO_TYPE_GL_BASEITEM type I value 104. "#EC NOTEXT
  constants CO_TYPE_GL_BASE_SUBTYPE type I value 105. "#EC NOTEXT
  constants CO_TYPE_ME_FSOURCE type I value 106. "#EC NOTEXT
  constants CO_TYPE_ME_EADDOC type I value 107. "#EC NOTEXT
  constants CO_TYPE_ME_EPREPDOC type I value 108. "#EC NOTEXT
  constants CO_TYPE_ME_DRUGDOC type I value 109. "#EC NOTEXT
  constants CO_TYPE_ME_TPGROUP type I value 110. "#EC NOTEXT
  constants CO_TYPE_DWS_PROFILE type I value 111. "#EC NOTEXT
  constants CO_TYPE_DWS_PATTERN type I value 112. "#EC NOTEXT
  constants CO_TYPE_APPLAN type I value 113. "#EC NOTEXT
  constants CO_TYPE_AN_FINDING type I value 114. "#EC NOTEXT
  constants CO_TYPE_AN_TEMPLATE type I value 115. "#EC NOTEXT
  constants CO_TYPE_AN_GRAPHIC type I value 116. "#EC NOTEXT
  constants CO_TYPE_DWS_GROUP type I value 117. "#EC NOTEXT
  constants CO_TYPE_BASEITEMTYPE type I value 118. "#EC NOTEXT
  constants CO_TYPE_BASEITEM type I value 119. "#EC NOTEXT
  constants CO_TYPE_DWS_COMP type I value 120. "#EC NOTEXT
  constants CO_TYPE_PROGRESS_DOCUMENT type I value 121. "#EC NOTEXT
  constants CO_TYPE_PROGRESS_ENTRY type I value 122. "#EC NOTEXT
  constants CO_TYPE_OFFICE_DOCUMENT type I value 123. "#EC NOTEXT
  constants CO_TYPE_DWS_SITUATION type I value 124. "#EC NOTEXT
  constants CO_TYPE_ME_PRPRINT type I value 125. "#EC NOTEXT
  constants CO_TYPE_DWS_INFO type I value 126. "#EC NOTEXT
  constants CO_TYPE_APP_CONSTRAINT_D type I value 127. "#EC NOTEXT
  constants CO_TYPE_DWS_COMP_WL type I value 128. "#EC NOTEXT
  constants CO_TYPE_DWS_COMP_PV type I value 129. "#EC NOTEXT
  constants CO_TYPE_PROBLEM type I value 130. "#EC NOTEXT
  constants CO_TYPE_BASEITEMCAT type I value 131. "#EC NOTEXT
  constants CO_TYPE_ADM_SERVICE type I value 132. "#EC NOTEXT
  constants CO_TYPE_DWS_COMP_CTX type I value 133. "#EC NOTEXT
  constants CO_TYPE_URL type I value 134. "#EC NOTEXT
  constants CO_TYPE_STRUCMEDREC type I value 135. "#EC NOTEXT
  constants CO_TYPE_TRANSACTION type I value 136. "#EC NOTEXT
  constants CO_TYPE_DWS_COMP_MONITOR type I value 137. "#EC NOTEXT
  constants CO_TYPE_DWS_COMP_OPTIONS type I value 138. "#EC NOTEXT
  constants CO_TYPE_DWS_BADI type I value 139. "#EC NOTEXT
  constants CO_TYPE_DWS_WORK type I value 140. "#EC NOTEXT
  constants CO_TYPE_DWS_PATHWAY type I value 141. "#EC NOTEXT
  constants CO_TYPE_DWS_TASK type I value 142. "#EC NOTEXT
  constants CO_TYPE_DWS_PRINT type I value 143. "#EC NOTEXT
  constants CO_TYPE_ACCIDENT type I value 144. "#EC NOTEXT
  constants CO_TYPE_REDOMA type I value 145. "#EC NOTEXT
  constants CO_NONE_OO_NBEW type I value 500. "#EC NOTEXT
  constants CO_NONE_OO_FREELINE_PLAN type I value 501. "#EC NOTEXT
  constants CO_NONE_OO_NFAL type I value 502. "#EC NOTEXT
  constants CO_NONE_OO_NPAT type I value 503. "#EC NOTEXT
  constants CO_NONE_OO_NDOC type I value 504. "#EC NOTEXT
  constants CO_NONE_OO_N2VDNOTE type I value 505. "#EC NOTEXT
  constants CO_DSPOBJ_OPERATION type I value 1000. "#EC NOTEXT
  constants CO_DSPOBJ_APPOINTMENT type I value 1001. "#EC NOTEXT
  constants CO_DSPOBJ_FREELINE_PLAN type I value 1002. "#EC NOTEXT
  constants CO_DISPLAY_OP type I value 1500. "#EC NOTEXT
  constants CO_DISPLAY_WPOOL_OP type I value 1501. "#EC NOTEXT
  constants CO_TYPE_CONT_ENVIRONMENT type I value 2000. "#EC NOTEXT
  constants CO_TYPE_CONT_MANAGER type I value 2001. "#EC NOTEXT
  constants CO_TYPE_CONT_CANCEL type I value 2002. "#EC NOTEXT
  constants CO_TYPE_CONT_COMMON type I value 2003. "#EC NOTEXT
  constants CO_TYPE_CONT_CASE_CHG_ISH type I value 2004. "#EC NOTEXT
  constants CO_TYPE_CONT_CASE_CHG_MED type I value 2005. "#EC NOTEXT
  constants CO_TYPE_BASIS_TEXTMODULE type I value 3000. "#EC NOTEXT
  constants CO_TYPE_DATA_OBJECT type I value 3001. "#EC NOTEXT
  constants CO_TYPE_MASTER_DATA type I value 3002. "#EC NOTEXT
  constants CO_TYPE_RUN_DATA type I value 3003. "#EC NOTEXT
  constants CO_TYPE_CONFIG type I value 3004. "#EC NOTEXT
  constants CO_TYPE_SCREEN type I value 3005. "#EC NOTEXT
  constants CO_TYPE_SCREEN_CUST type I value 3006. "#EC NOTEXT
  constants CO_TYPE_SCREEN_STD type I value 3007. "#EC NOTEXT
  constants CO_TYPE_FIELD_VALUES type I value 3008. "#EC NOTEXT
  constants CO_TYPE_COMPONENT type I value 3009. "#EC NOTEXT
  constants CO_TYPE_COMPONENT_STD type I value 3010. "#EC NOTEXT
  constants CO_TYPE_COMPONENT_CUST type I value 3011. "#EC NOTEXT
  constants CO_TYPE_SCREEN_COLLAPSIBLE_STD type I value 3012. "#EC NOTEXT
  constants CO_TYPE_SCR_CONTROL type I value 3013. "#EC NOTEXT
  constants CO_TYPE_SCR_ALV_CONTROL type I value 3014. "#EC NOTEXT
  constants CO_TYPE_SCR_ALV_GRID type I value 3015. "#EC NOTEXT
  constants CO_TYPE_SCR_ALV_TREE type I value 3016. "#EC NOTEXT
  constants CO_TYPE_CONFIG_SPLITTER type I value 3017. "#EC NOTEXT
  constants CO_TYPE_SCR_SPLITTER type I value 3018. "#EC NOTEXT
  constants CO_TYPE_CONFIG_ALV_GRID type I value 3019. "#EC NOTEXT
  constants CO_TYPE_COMPONENT_BASE type I value 3020. "#EC NOTEXT
  constants CO_TYPE_CONFIG_ALV_TREE type I value 3021. "#EC NOTEXT
  constants CO_TYPE_SCR_HTML type I value 3022. "#EC NOTEXT
  constants CO_TYPE_COMPONENT_CONFIG type I value 3023. "#EC NOTEXT
  constants CO_TYPE_DWS_PROCESS type I value 3024. "#EC NOTEXT
  constants CO_TYPE_CONFIG_HTML type I value 3025. "#EC NOTEXT
  constants CO_TYPE_PLANNING_GRID type I value 4000. "#EC NOTEXT
  constants CO_TYPE_MSCHED type I value 4001. "#EC NOTEXT
  constants CO_TYPE_APP_OFFER_HANDLING type I value 4002. "#EC NOTEXT
  constants CO_TYPE_DYN_CONTAINER type I value 4003. "#EC NOTEXT
  constants CO_TYPE_DD_OBJ_SCR_TEAM type I value 4004. "#EC NOTEXT
  constants CO_TYPE_DD_OBJ_DISPLAY type I value 4005. "#EC NOTEXT
  constants CO_TYPE_PLANNING_LIST type I value 4006. "#EC NOTEXT
  constants CO_TYPE_SNAPSHOT_HANDLING type I value 4007. "#EC NOTEXT
  constants CO_TYPE_SRV_CHOICE_LIST_CONT type I value 4008. "#EC NOTEXT
  constants CO_TYPE_STRUCTURE_MEDREC type I value 4009. "#EC NOTEXT
  constants CO_TYPE_CONTEXT_MEDSRV type I value 4010. "#EC NOTEXT
  constants CO_TYPE_GRID_BUTTONHANDLER type I value 4011. "#EC NOTEXT
  constants CO_TYPE_GRID_BUTTONDEF type I value 4012. "#EC NOTEXT
  constants CO_TYPE_GRID_BUTTON type I value 4013. "#EC NOTEXT
  constants CO_TYPE_GRID_KEYBUTTONDEF type I value 4014. "#EC NOTEXT
  constants CO_TYPE_GRID_KEYBUTTON type I value 4015. "#EC NOTEXT
  constants CO_TYPE_GRID_TOGGLEBUTTONDEF type I value 4016. "#EC NOTEXT
  constants CO_TYPE_GRID_TOGGLEBUTTON type I value 4017. "#EC NOTEXT
  constants CO_TYPE_GRID_LTXBUTTONDEF type I value 4018. "#EC NOTEXT
  constants CO_TYPE_GRID_LTXBUTTON type I value 4019. "#EC NOTEXT
  constants CO_TYPE_GRID_LISTBOXHANDLER type I value 4020. "#EC NOTEXT
  constants CO_TYPE_DWS_PATIENTVIEWER type I value 4021. "#EC NOTEXT
  constants CO_TYPE_APP_OFFER_HANDLING_MED type I value 4022. "#EC NOTEXT
  constants CO_TYPE_PLANNING_LIST_MED type I value 4023. "#EC NOTEXT
  constants CO_TYPE_GRID_CELLMERGER type I value 4024. "#EC NOTEXT
  constants CO_TYPE_GRID_SELECTOR type I value 4025. "#EC NOTEXT
  constants CO_TYPE_DND type I value 4026. "#EC NOTEXT
  constants CO_TYPE_DND_GRID type I value 4027. "#EC NOTEXT
  constants CO_TYPE_DND_TREE type I value 4028. "#EC NOTEXT
  constants CO_TYPE_DND_TREE_SINGLE type I value 4029. "#EC NOTEXT
  constants CO_TYPE_DND_TREE_MULT type I value 4030. "#EC NOTEXT
  constants CO_TYPE_DNDEV type I value 4031. "#EC NOTEXT
  constants CO_TYPE_DNDEV_GRID type I value 4032. "#EC NOTEXT
  constants CO_TYPE_DNDEV_TREE type I value 4033. "#EC NOTEXT
  constants CO_TYPE_CONNECTIVITY type I value 4034. "#EC NOTEXT
  constants CO_TYPE_CONNECTIVITY_MED type I value 4035. "#EC NOTEXT
  constants CO_TYPE_FCT_PLANNING type I value 5000. "#EC NOTEXT
  constants CO_TYPE_FCT_GUIDELINE type I value 5001. "#EC NOTEXT
  constants CO_TYPE_FCT_CORDER type I value 5002. "#EC NOTEXT
  constants CO_TYPE_FCT_CORDER_MED type I value 5003. "#EC NOTEXT
  constants CO_TYPE_FCT_GL_TREATMENT type I value 5004. "#EC NOTEXT
  constants CO_TYPE_FCT_TEAM type I value 5005. "#EC NOTEXT
  constants CO_TYPE_FCT_MVM4APP type I value 5006. "#EC NOTEXT
  constants CO_TYPE_FCT_MVM4APP_MED type I value 5007. "#EC NOTEXT
  constants CO_TYPE_FCT_GL_ASSIGN type I value 5008. "#EC NOTEXT
  constants CO_TYPE_FCT_GL_BASE type I value 5009. "#EC NOTEXT
  constants CO_TYPE_FCT_GL_MONITOR type I value 5010. "#EC NOTEXT
  constants CO_TYPE_FCT_GL_PATH type I value 5011. "#EC NOTEXT
  constants CO_TYPE_FCT_PLANNING_MED type I value 5012. "#EC NOTEXT
  constants CO_TYPE_FCT_AN_FINDING type I value 5013. "#EC NOTEXT
  constants CO_TYPE_FCT_AN_TEMPLATE type I value 5014. "#EC NOTEXT
  constants CO_TYPE_FCT_MEDSRV_MED type I value 5015. "#EC NOTEXT
  constants CO_TYPE_FCT_APPLAN type I value 5016. "#EC NOTEXT
  constants CO_TYPE_FCT_ME_STATUS type I value 5017. "#EC NOTEXT
  constants CO_TYPE_FCT_AC type I value 5018. "#EC NOTEXT
  constants CO_TYPE_FCT_AC_MED type I value 5019. "#EC NOTEXT
  constants CO_TYPE_FCT_STRUCMEDREC type I value 5020. "#EC NOTEXT
  constants CO_TYPE_FCT_DWS_MEDSRV type I value 5021. "#EC NOTEXT
  constants CO_TYPE_PRC_PLANNING type I value 6000. "#EC NOTEXT
  constants CO_TYPE_PRC_PLANNING_FUNC type I value 6001. "#EC NOTEXT
  constants CO_TYPE_PRC_SET_CASE_REF type I value 6002. "#EC NOTEXT
  constants CO_TYPE_PRC_SET_CASE_REF_MED type I value 6003. "#EC NOTEXT
  constants CO_TYPE_PRC_CORDER type I value 6004. "#EC NOTEXT
  constants CO_TYPE_PRC_ORDER type I value 6005. "#EC NOTEXT
  constants CO_TYPE_PRC_TRANS_TYPE type I value 6036. "#EC NOTEXT
  constants CO_TYPE_PRC_ADMISSION type I value 6006. "#EC NOTEXT
  constants CO_TYPE_PRC_PATIENT type I value 6007. "#EC NOTEXT
  constants CO_TYPE_PRC_RADIOLOGY type I value 6008. "#EC NOTEXT
  constants CO_TYPE_PRC_CORDER_MED type I value 6009. "#EC NOTEXT
  constants CO_TYPE_PRC_SERVICES type I value 6010. "#EC NOTEXT
  constants CO_TYPE_PRC_REFERRAL type I value 6011. "#EC NOTEXT
  constants CO_TYPE_PRC_WAITING_LIST type I value 6012. "#EC NOTEXT
  constants CO_TYPE_PRC_TEAM type I value 6013. "#EC NOTEXT
  constants CO_TYPE_PRC_MVM4APP type I value 6014. "#EC NOTEXT
  constants CO_TYPE_PRC_MVM4APP_MED type I value 6015. "#EC NOTEXT
  constants CO_TYPE_PRC_INSURANCE type I value 6016. "#EC NOTEXT
  constants CO_TYPE_PRC_PROCEDURES type I value 6017. "#EC NOTEXT
  constants CO_TYPE_PRC_SURGERY_CHAR type I value 6018. "#EC NOTEXT
  constants CO_TYPE_PRC_COMMENT type I value 6019. "#EC NOTEXT
  constants CO_TYPE_PRC_MED_DATA type I value 6020. "#EC NOTEXT
  constants CO_TYPE_PRC_TRANS_ORDER type I value 6021. "#EC NOTEXT
  constants CO_TYPE_PRC_SURGERY_TEAM type I value 6022. "#EC NOTEXT
  constants CO_TYPE_PRC_ME_ORDER_DIALOG type I value 6023. "#EC NOTEXT
  constants CO_TYPE_PRC_ME_ADMIN_EVENT type I value 6024. "#EC NOTEXT
  constants CO_TYPE_PRC_PLANNING_DIALOG type I value 6025. "#EC NOTEXT
  constants CO_TYPE_PRC_PLANNING_MED type I value 6026. "#EC NOTEXT
  constants CO_TYPE_PRC_PLANNING_DIALOG_MD type I value 6027. "#EC NOTEXT
  constants CO_TYPE_PRC_MEDSRV_MED type I value 6028. "#EC NOTEXT
  constants CO_TYPE_PRC_MEDSRV_DIALOG_MED type I value 6029. "#EC NOTEXT
  constants CO_TYPE_PRC_STRUCMEDREC type I value 6030. "#EC NOTEXT
  constants CO_TYPE_PRC_STRUCMEDREC_DIALOG type I value 6031. "#EC NOTEXT
  constants CO_TYPE_PRC_POPUP type I value 6032. "#EC NOTEXT
  constants CO_TYPE_PRC_APPLAN type I value 6033. "#EC NOTEXT
  constants CO_TYPE_PRC_APPLAN_DIALOG type I value 6034. "#EC NOTEXT
  constants CO_TYPE_PRC_CORDER_AGGREG type I value 6035. "#EC NOTEXT
  constants CO_TYPE_PRC_POPUP_GPOE type I value 6036. "#EC NOTEXT
  constants CO_TYPE_PRC_ME_STATUS type I value 6037. "#EC NOTEXT
  constants CO_TYPE_PRC_AC type I value 6038. "#EC NOTEXT
  constants CO_TYPE_PRC_AC_MED type I value 6039. "#EC NOTEXT
  constants CO_TYPE_PRC_AC_DIALOG type I value 6040. "#EC NOTEXT
  constants CO_TYPE_PRC_AC_DIALOG_MED type I value 6041. "#EC NOTEXT
  constants CO_TYPE_PRC_POPUP_APPS_SEL type I value 6042. "#EC NOTEXT
  constants CO_TYPE_PRC_POPUP_ACD_LIST type I value 6043. "#EC NOTEXT
  constants CO_TYPE_PRC_CORDER_BASE_ITEM type I value 6044. "#EC NOTEXT
  constants CO_TYPE_PRC_DWS_MEDSRV type I value 6045. "#EC NOTEXT
  constants CO_TYPE_PRC_DWS_STRUCMEDREC type I value 6046. "#EC NOTEXT
  constants CO_TYPE_PRC_POPUP_SRVHITLS_MED type I value 6047. "#EC NOTEXT
  constants CO_TYPE_SCR_MED_TEXT type I value 7000. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_DATA_HANDLER type I value 7001. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_BASIC type I value 7002. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_COMMENT type I value 7003. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_NOTIFICATION type I value 7004. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_PROTOCOL type I value 7005. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_NOTIF_PROT type I value 7006. "#EC NOTEXT
  constants CO_TYPE_SCR_ADMISSION type I value 7007. "#EC NOTEXT
  constants CO_TYPE_SCR_PRIO_TRANSP type I value 7008. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_BASIC_MED type I value 7009. "#EC NOTEXT
  constants CO_TYPE_SCR_ORDER type I value 7010. "#EC NOTEXT
  constants CO_TYPE_SCR_PARTNER type I value 7011. "#EC NOTEXT
  constants CO_TYPE_SCR_TRANS_TYPE type I value 7012. "#EC NOTEXT
  constants CO_TYPE_SCR_PATIENT type I value 7013. "#EC NOTEXT
  constants CO_TYPE_SCR_RADIOLOGY type I value 7014. "#EC NOTEXT
  constants CO_TYPE_SCR_PATIENT_ADDON type I value 7015. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDHEAD_COLL type I value 7016. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDHEAD_SHORT type I value 7017. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDHEAD_DETAIL type I value 7018. "#EC NOTEXT
  constants CO_TYPE_SCR_PLANNER type I value 7019. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_NOTIF_PROT_MED type I value 7020. "#EC NOTEXT
  constants CO_TYPE_SCR_SERVICES type I value 7021. "#EC NOTEXT
  constants CO_TYPE_SCR_SERVICE_DETAIL type I value 7022. "#EC NOTEXT
  constants CO_TYPE_SCR_REFERRAL type I value 7023. "#EC NOTEXT
  constants CO_TYPE_SCR_TASK type I value 7024. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EXPORDERH type I value 7025. "#EC NOTEXT
  constants CO_TYPE_SCR_CYCLE type I value 7026. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDPOS_COLL type I value 7027. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDPOS_SHORT type I value 7028. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDPOS_DETAIL type I value 7029. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_INFUSION type I value 7030. "#EC NOTEXT
  constants CO_TYPE_SCR_TEAM type I value 7031. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDPOS_SHORT_MED type I value 7032. "#EC NOTEXT
  constants CO_TYPE_SCR_APPTXT type I value 7033. "#EC NOTEXT
  constants CO_TYPE_SCR_APPDTZT type I value 7034. "#EC NOTEXT
  constants CO_TYPE_SCR_WDISP type I value 7035. "#EC NOTEXT
  constants CO_TYPE_SCR_WPTINP type I value 7036. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDPOS_CASE type I value 7037. "#EC NOTEXT
  constants CO_TYPE_SCR_WAITING_LIST type I value 7038. "#EC NOTEXT
  constants CO_TYPE_SCR_TABSTRIP type I value 7039. "#EC NOTEXT
  constants CO_TYPE_SCR_INSURANCE type I value 7040. "#EC NOTEXT
  constants CO_TYPE_SCR_CORD_DESEL type I value 7041. "#EC NOTEXT
  constants CO_TYPE_SCR_REGISTER_PATIENT type I value 7042. "#EC NOTEXT
  constants CO_TYPE_SCR_PROCEDURES type I value 7043. "#EC NOTEXT
  constants CO_TYPE_SCR_SURGERY_CHAR type I value 7044. "#EC NOTEXT
  constants CO_TYPE_SCR_COMMENT type I value 7045. "#EC NOTEXT
  constants CO_TYPE_SCR_MED_DATA type I value 7046. "#EC NOTEXT
  constants CO_TYPE_SCR_TRANS_ORDER type I value 7047. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_TPN type I value 7048. "#EC NOTEXT
  constants CO_TYPE_SCR_SURGERY_TEAM type I value 7049. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_AGENT type I value 7050. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_ADDITIVE type I value 7051. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_AGENT_GRID type I value 7052. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_DOSECALC type I value 7053. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_DOSECALC_IV type I value 7054. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_DOSEC_HEAD type I value 7055. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_INGRED_GRID type I value 7056. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_ORATE type I value 7057. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_ORADE_GRID type I value 7058. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_ORATE_PCA type I value 7059. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_ORATE_VOL type I value 7060. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_ORDER_GRID type I value 7061. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_PRESCR type I value 7062. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EXTEMP_COMP type I value 7063. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDPOS_APP type I value 7064. "#EC NOTEXT
  constants CO_TYPE_SCR_APPOINTMENT_LIST type I value 7065. "#EC NOTEXT
  constants CO_TYPE_SCR_PLN_LIST_TABSTR type I value 7066. "#EC NOTEXT
  constants CO_TYPE_SCR_PLN_LIST_APP_DET type I value 7067. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_HDR type I value 7068. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_ADDINFO type I value 7069. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_SIG type I value 7070. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_STD type I value 7071. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_MDA type I value 7072. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_DOCHD type I value 7073. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_DA_EMARTAB type I value 7074. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_MDA_GRID type I value 7075. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_STANDARD type I value 7076. "#EC NOTEXT
  constants CO_TYPE_SCR_CONTEXT type I value 7077. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_PUMPRATE_GRID type I value 7078. "#EC NOTEXT
  constants CO_TYPE_SCR_LISTBOX type I value 7079. "#EC NOTEXT
  constants CO_TYPE_SCR_PUSHBUTTON type I value 7080. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EVENT_DATA type I value 7081. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EVENT_GRID type I value 7082. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_ORDER_DETAIL type I value 7083. "#EC NOTEXT
  constants CO_TYPE_SCR_DIV_HW type I value 7084. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDER_USER type I value 7085. "#EC NOTEXT
  constants CO_TYPE_SCR_PATIENT_COLLAPS type I value 7086. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_TMPL_DESCR type I value 7087. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_SHOW_TIMELINE type I value 7088. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_RATE_CHANGE type I value 7089. "#EC NOTEXT
  constants CO_TYPE_SCR_DWS_MEDSRV type I value 7090. "#EC NOTEXT
  constants CO_TYPE_SCR_DWS_MEDSRV_WORK type I value 7091. "#EC NOTEXT
  constants CO_TYPE_SCR_SPLITTER_SIMPLE type I value 7092. "#EC NOTEXT
  constants CO_TYPE_SCR_ALV_GRID_SIMPLE type I value 7093. "#EC NOTEXT
  constants CO_TYPE_SCR_CAUSE_CHANGE type I value 7094. "#EC NOTEXT
  constants CO_TYPE_SCR_STRUCMEDREC type I value 7095. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_MED type I value 7096. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_WORK_MED type I value 7097. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_HITLS_MED type I value 7098. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_INFO_MED type I value 7099. "#EC NOTEXT
  constants CO_TYPE_SCR_APPLAN type I value 7100. "#EC NOTEXT
  constants CO_TYPE_SCR_PATIENT_AGGREG type I value 7101. "#EC NOTEXT
  constants CO_TYPE_SCR_CORDER_GPOE type I value 7102. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_DOSECALC_COMP type I value 7103. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_PROP type I value 7104. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_PRE type I value 7105. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_DATA_HANDLER_M type I value 7106. "#EC NOTEXT
  constants CO_TYPE_SCR_PAT_HTML_HEADER type I value 7107. "#EC NOTEXT
  constants CO_TYPE_SCR_COMPCON_MEDSRV type I value 7108. "#EC NOTEXT
  constants CO_TYPE_SCR_ORDER_MED type I value 7109. "#EC NOTEXT
  constants CO_TYPE_SCR_AC_HANDLER type I value 7110. "#EC NOTEXT
  constants CO_TYPE_SCR_AC_HANDLER_MED type I value 7111. "#EC NOTEXT
  constants CO_TYPE_SCR_AC type I value 7112. "#EC NOTEXT
  constants CO_TYPE_SCR_AC_D type I value 7113. "#EC NOTEXT
  constants CO_TYPE_SCR_AC_MED type I value 7114. "#EC NOTEXT
  constants CO_TYPE_SCR_AC_D_MED type I value 7115. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_AO_LIST type I value 7116. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_AO_LIST_M type I value 7117. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EVENT_LIST_OS type I value 7118. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EVENT_LIST type I value 7119. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_HITLS_DEF type I value 7120. "#EC NOTEXT
  constants CO_TYPE_SCR_MEDSRV_CTX type I value 7121. "#EC NOTEXT
  constants CO_TYPE_SCR_DWS_CCON_MEDSRV type I value 7122. "#EC NOTEXT
  constants CO_TYPE_SCR_DWS_MEDSRV_PROP type I value 7123. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_DETAILS_MED type I value 7124. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_DETAILS type I value 7125. "#EC NOTEXT
  constants CO_TYPE_SCR_SPLIT_APP_AO_LIST type I value 7126. "#EC NOTEXT
  constants CO_TYPE_SCR_TAB_APP_AO_LIST type I value 7127. "#EC NOTEXT
  constants CO_TYPE_SCR_ME_EMAR_HD_STD type I value 7128. "#EC NOTEXT
  constants CO_TYPE_SCR_PATIENT_BASE_ITEM type I value 7129. "#EC NOTEXT
  constants CO_TYPE_SCR_APP_BASIC_ADM type I value 7130. "#EC NOTEXT
  constants CO_TYPE_COMP_PATIENT type I value 8000. "#EC NOTEXT
  constants CO_TYPE_COMP_ORDER type I value 8001. "#EC NOTEXT
  constants CO_TYPE_COMP_MED_DATA type I value 8002. "#EC NOTEXT
  constants CO_TYPE_COMP_ADMISSION type I value 8003. "#EC NOTEXT
  constants CO_TYPE_COMP_WAITING_LIST type I value 8004. "#EC NOTEXT
  constants CO_TYPE_COMP_REFERRAL type I value 8005. "#EC NOTEXT
  constants CO_TYPE_COMP_INSURANCE type I value 8006. "#EC NOTEXT
  constants CO_TYPE_COMP_PROCEDURES type I value 8007. "#EC NOTEXT
  constants CO_TYPE_COMP_COMMENT type I value 8008. "#EC NOTEXT
  constants CO_TYPE_COMP_CONTEXT type I value 8009. "#EC NOTEXT
  constants CO_TYPE_COMP_SERVICES type I value 8010. "#EC NOTEXT
  constants CO_TYPE_COMP_RADIOLOGY type I value 8011. "#EC NOTEXT
  constants CO_TYPE_COMP_TRANS_ORDER type I value 8012. "#EC NOTEXT
  constants CO_TYPE_COMP_TRANS_TYPE type I value 8013. "#EC NOTEXT
  constants CO_TYPE_COMP_SURGERY_TEAM type I value 8014. "#EC NOTEXT
  constants CO_TYPE_COMP_SURGERY_CHAR type I value 8015. "#EC NOTEXT
  constants CO_TYPE_COMP_CORDER_USER type I value 8016. "#EC NOTEXT
  constants CO_TYPE_COMP_DWS_MEDSRV type I value 8017. "#EC NOTEXT
  constants CO_TYPE_COMP_STRUCMEDREC type I value 8018. "#EC NOTEXT
  constants CO_TYPE_COMP_MEDSRV_MED type I value 8019. "#EC NOTEXT
  constants CO_TYPE_COMP_PATIENT_AGGREG type I value 8020. "#EC NOTEXT
  constants CO_TYPE_COMPCON_MEDSRV type I value 8021. "#EC NOTEXT
  constants CO_TYPE_COMP_ORDER_MED type I value 8022. "#EC NOTEXT
  constants CO_TYPE_COMPCON_DWS_MEDSRV type I value 8023. "#EC NOTEXT
  constants CO_TYPE_COMP_PATIENT_BASE_ITEM type I value 8024. "#EC NOTEXT
  constants CO_TYPE_CON_CORDER type I value 9000. "#EC NOTEXT
  constants CO_TYPE_CON_PLANNING_GRID type I value 9001. "#EC NOTEXT
  constants CO_TYPE_CON_PLANNING_LIST type I value 9002. "#EC NOTEXT
  constants CO_TYPE_CON_CORDER_MED type I value 9003. "#EC NOTEXT
  constants CO_TYPE_CON_APP_EDITOR type I value 9004. "#EC NOTEXT
  constants CO_TYPE_CON_APP_EDITOR_MED type I value 9005. "#EC NOTEXT
  constants CO_TYPE_CON_APP_EDITOR_PG type I value 9006. "#EC NOTEXT
  constants CO_TYPE_CON_APP_EDITOR_PL type I value 9007. "#EC NOTEXT
  constants CO_TYPE_CON_PLANGRID_WP014 type I value 9008. "#EC NOTEXT
  constants CO_TYPE_CON_MEDSRV_MED type I value 9009. "#EC NOTEXT
  constants CO_TYPE_CON_SCR_MEDSRV_MED type I value 9010. "#EC NOTEXT
  constants CO_TYPE_CON_SRC_MEDSRV_WRK_MED type I value 9011. "#EC NOTEXT
  constants CO_TYPE_CON_APP_EDITOR_MULTI type I value 9012. "#EC NOTEXT
  constants CO_TYPE_CON_APP_EDITOR_MULTI_M type I value 9013. "#EC NOTEXT
  constants CO_TYPE_CON_APP_LIST type I value 9014. "#EC NOTEXT
  constants CO_TYPE_CON_APP_LIST_M type I value 9015. "#EC NOTEXT
  constants CO_TYPE_CON_AO_LIST type I value 9016. "#EC NOTEXT
  constants CO_TYPE_CON_AO_LIST_M type I value 9017. "#EC NOTEXT
  constants CO_TYPE_CON_ME_EVENT_LIST type I value 9018. "#EC NOTEXT
  constants CO_TYPE_CON_APP_LIST_SEL type I value 9019. "#EC NOTEXT
  constants CO_TYPE_CON_PLANNING_LIST_MED type I value 9020. "#EC NOTEXT
  constants CO_TYPE_CON_CORDER_MED_AGGREG type I value 9021. "#EC NOTEXT
  constants CO_TYPE_CON_CORDER_BASE_ITEM type I value 9022. "#EC NOTEXT
  constants CO_TYPE_CON_CANCEL type I value 9023. "#EC NOTEXT
  constants CO_TYPE_CON_CANCEL_MED type I value 9024. "#EC NOTEXT
  constants CO_TYPE_DWS_CTR_MEDSRV type I value 10000. "#EC NOTEXT
  constants CO_TYPE_DWS_CTR_STRUCMEDREC type I value 10001. "#EC NOTEXT
  constants CO_TYPE_ERROR type I value 11000. "#EC NOTEXT
  constants CO_TYPE_ERROR_APMG type I value 11001. "#EC NOTEXT
  constants CO_TYPE_ERROR_APMG_MED type I value 11002. "#EC NOTEXT
  constants CO_TYPE_CUSTOMER_OBJECTS type I value 30000. "#EC NOTEXT
  constants CO_TYPE_CON_CORDTPL type I value 13530. "#EC NOTEXT
  constants CO_TYPE_PRC_CORDTPL type I value 13531. "#EC NOTEXT
  constants CO_TYPE_CORDTPL type I value 13532. "#EC NOTEXT
endinterface.
