*"* components of interface IF_ISH_GUI_TABSTRIP_VIEW
interface IF_ISH_GUI_TABSTRIP_VIEW
  public .


  interfaces IF_ISH_GUI_SDY_VIEW .

  aliases CO_UCOMM_POV_PROCESSED
    for IF_ISH_GUI_SDY_VIEW~CO_UCOMM_POV_PROCESSED .
  aliases CO_VCODE_DISPLAY
    for IF_ISH_GUI_SDY_VIEW~CO_VCODE_DISPLAY .
  aliases CO_VCODE_INSERT
    for IF_ISH_GUI_SDY_VIEW~CO_VCODE_INSERT .
  aliases CO_VCODE_UPDATE
    for IF_ISH_GUI_SDY_VIEW~CO_VCODE_UPDATE .
  aliases DESTROY
    for IF_ISH_GUI_SDY_VIEW~DESTROY .
  aliases GET_APPLICATION
    for IF_ISH_GUI_SDY_VIEW~GET_APPLICATION .
  aliases GET_CHILD_VIEWS
    for IF_ISH_GUI_SDY_VIEW~GET_CHILD_VIEWS .
  aliases GET_CHILD_VIEW_BY_ID
    for IF_ISH_GUI_SDY_VIEW~GET_CHILD_VIEW_BY_ID .
  aliases GET_CHILD_VIEW_BY_NAME
    for IF_ISH_GUI_SDY_VIEW~GET_CHILD_VIEW_BY_NAME .
  aliases GET_CONTROLLER
    for IF_ISH_GUI_SDY_VIEW~GET_CONTROLLER .
  aliases GET_DYNNR
    for IF_ISH_GUI_SDY_VIEW~GET_DYNNR .
  aliases GET_ELEMENT_ID
    for IF_ISH_GUI_SDY_VIEW~GET_ELEMENT_ID .
  aliases GET_ELEMENT_NAME
    for IF_ISH_GUI_SDY_VIEW~GET_ELEMENT_NAME .
  aliases GET_LAYOUT
    for IF_ISH_GUI_SDY_VIEW~GET_LAYOUT .
  aliases GET_PARENT_VIEW
    for IF_ISH_GUI_SDY_VIEW~GET_PARENT_VIEW .
  aliases GET_REPID
    for IF_ISH_GUI_SDY_VIEW~GET_REPID .
  aliases GET_VCODE
    for IF_ISH_GUI_SDY_VIEW~GET_VCODE .
  aliases HAS_FOCUS
    for IF_ISH_GUI_SDY_VIEW~HAS_FOCUS .
  aliases IS_DESTROYED
    for IF_ISH_GUI_SDY_VIEW~IS_DESTROYED .
  aliases IS_INITIALIZED
    for IF_ISH_GUI_SDY_VIEW~IS_INITIALIZED .
  aliases IS_IN_DESTROY_MODE
    for IF_ISH_GUI_SDY_VIEW~IS_IN_DESTROY_MODE .
  aliases IS_IN_INITIALIZATION_MODE
    for IF_ISH_GUI_SDY_VIEW~IS_IN_INITIALIZATION_MODE .
  aliases PROCESS_REQUEST
    for IF_ISH_GUI_SDY_VIEW~PROCESS_REQUEST .
  aliases REGISTER_CHILD_VIEW
    for IF_ISH_GUI_SDY_VIEW~REGISTER_CHILD_VIEW .
  aliases SET_FOCUS
    for IF_ISH_GUI_SDY_VIEW~SET_FOCUS .
  aliases SET_VCODE
    for IF_ISH_GUI_SDY_VIEW~SET_VCODE .
  aliases EV_AFTER_DESTROY
    for IF_ISH_GUI_SDY_VIEW~EV_AFTER_DESTROY .
  aliases EV_BEFORE_DESTROY
    for IF_ISH_GUI_SDY_VIEW~EV_BEFORE_DESTROY .

  events EV_ACTIVETAB_CHANGED
    exporting
      value(E_OLD_ACTIVETAB) type N1GUI_ELEMENT_NAME
      value(E_NEW_ACTIVETAB) type N1GUI_ELEMENT_NAME .

  methods GET_ACTIVE_TAB_NAME
    returning
      value(R_ACTIVE_TAB_NAME) type N1GUI_ELEMENT_NAME .
  methods GET_ACTIVE_TAB_VIEW
    returning
      value(RR_ACTIVE_TAB_VIEW) type ref to IF_ISH_GUI_SDY_VIEW .
  type-pools ABAP .
  methods SET_ACTIVE_TAB_BY_NAME
    importing
      !I_TAB_NAME type N1GUI_ELEMENT_NAME
      !I_SET_FOCUS type ABAP_BOOL default ABAP_TRUE
    returning
      value(RR_ACTIVE_TAB_VIEW) type ref to IF_ISH_GUI_SDY_VIEW
    raising
      CX_ISH_STATIC_HANDLER .
  methods SET_ACTIVE_TAB_BY_VIEW
    importing
      !IR_VIEW type ref to IF_ISH_GUI_SDY_VIEW
      !I_SET_FOCUS type ABAP_BOOL default ABAP_TRUE
    raising
      CX_ISH_STATIC_HANDLER .
endinterface.
