*"* components of interface IF_ISH_GUI_DYNPRO_VIEW
interface IF_ISH_GUI_DYNPRO_VIEW
  public .


  interfaces IF_ISH_GUI_VIEW .

  aliases CO_VCODE_DISPLAY
    for IF_ISH_GUI_VIEW~CO_VCODE_DISPLAY .
  aliases CO_VCODE_INSERT
    for IF_ISH_GUI_VIEW~CO_VCODE_INSERT .
  aliases CO_VCODE_UPDATE
    for IF_ISH_GUI_VIEW~CO_VCODE_UPDATE .
  aliases ACTUALIZE_LAYOUT
    for IF_ISH_GUI_VIEW~ACTUALIZE_LAYOUT .
  aliases DESTROY
    for IF_ISH_GUI_VIEW~DESTROY .
  aliases GET_APPLICATION
    for IF_ISH_GUI_VIEW~GET_APPLICATION .
  aliases GET_CHILD_VIEWS
    for IF_ISH_GUI_VIEW~GET_CHILD_VIEWS .
  aliases GET_CHILD_VIEW_BY_ID
    for IF_ISH_GUI_VIEW~GET_CHILD_VIEW_BY_ID .
  aliases GET_CHILD_VIEW_BY_NAME
    for IF_ISH_GUI_VIEW~GET_CHILD_VIEW_BY_NAME .
  aliases GET_CONTROLLER
    for IF_ISH_GUI_VIEW~GET_CONTROLLER .
  aliases GET_ELEMENT_ID
    for IF_ISH_GUI_VIEW~GET_ELEMENT_ID .
  aliases GET_ELEMENT_NAME
    for IF_ISH_GUI_VIEW~GET_ELEMENT_NAME .
  aliases GET_LAYOUT
    for IF_ISH_GUI_VIEW~GET_LAYOUT .
  aliases GET_PARENT_VIEW
    for IF_ISH_GUI_VIEW~GET_PARENT_VIEW .
  aliases GET_VCODE
    for IF_ISH_GUI_VIEW~GET_VCODE .
  aliases HAS_FOCUS
    for IF_ISH_GUI_VIEW~HAS_FOCUS .
  aliases IS_DESTROYED
    for IF_ISH_GUI_VIEW~IS_DESTROYED .
  aliases IS_INITIALIZED
    for IF_ISH_GUI_VIEW~IS_INITIALIZED .
  aliases IS_IN_DESTROY_MODE
    for IF_ISH_GUI_VIEW~IS_IN_DESTROY_MODE .
  aliases IS_IN_INITIALIZATION_MODE
    for IF_ISH_GUI_VIEW~IS_IN_INITIALIZATION_MODE .
  aliases PROCESS_REQUEST
    for IF_ISH_GUI_VIEW~PROCESS_REQUEST .
  aliases REGISTER_CHILD_VIEW
    for IF_ISH_GUI_VIEW~REGISTER_CHILD_VIEW .
  aliases SET_FOCUS
    for IF_ISH_GUI_VIEW~SET_FOCUS .
  aliases SET_VCODE
    for IF_ISH_GUI_VIEW~SET_VCODE .
  aliases EV_AFTER_DESTROY
    for IF_ISH_GUI_VIEW~EV_AFTER_DESTROY .
  aliases EV_BEFORE_DESTROY
    for IF_ISH_GUI_VIEW~EV_BEFORE_DESTROY .

  constants CO_UCOMM_POV_PROCESSED type SYUCOMM value '$POV_PROCESSED'. "#EC NOTEXT

  methods COMPLETE_POV
    importing
      !I_REPID type SYREPID optional
      !I_DYNNR type SYDYNNR optional
      !IT_CHANGED_FIELD type ISH_T_DYNPREAD
    preferred parameter I_DYNNR
    raising
      CX_ISH_STATIC_HANDLER .
  methods GET_DYNNR
    returning
      value(R_DYNNR) type SY-DYNNR .
  methods GET_DYNPRO_LAYOUT
    returning
      value(RR_DYNPRO_LAYOUT) type ref to CL_ISH_GUI_DYNPRO_LAYOUT .
  methods GET_DYNPSTRUCT_FIELDNAME
    importing
      !I_FIELDNAME type ISH_FIELDNAME
    returning
      value(R_DYNPSTRUCT_FIELDNAME) type ISH_FIELDNAME .
  methods GET_DYNPSTRUCT_NAME
    returning
      value(R_DYNPSTRUCT_NAME) type TABNAME .
  methods GET_REPID
    returning
      value(R_REPID) type SY-REPID .
endinterface.
