*"* components of interface IF_ISH_RS_ENTITY
interface IF_ISH_RS_ENTITY
  public .


  interfaces IF_ISH_GUI_STRUCTURE_MODEL .
  interfaces IF_ISH_RS_OBJECT .

  aliases GET_FIELD_CONTENT
    for IF_ISH_GUI_STRUCTURE_MODEL~GET_FIELD_CONTENT .
  aliases GET_READ_SERVICE
    for IF_ISH_RS_OBJECT~GET_READ_SERVICE .
  aliases GET_SUPPORTED_FIELDS
    for IF_ISH_GUI_STRUCTURE_MODEL~GET_SUPPORTED_FIELDS .
  aliases IS_FIELD_SUPPORTED
    for IF_ISH_GUI_STRUCTURE_MODEL~IS_FIELD_SUPPORTED .
  aliases SET_FIELD_CONTENT
    for IF_ISH_GUI_STRUCTURE_MODEL~SET_FIELD_CONTENT .
  aliases EV_CHANGED
    for IF_ISH_GUI_STRUCTURE_MODEL~EV_CHANGED .
endinterface.
