*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LN1CUSTOMER_TYPESTOP.              " Global Data
  INCLUDE LN1CUSTOMER_TYPESUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LN1CUSTOMER_TYPESF00                    . " subprograms
  INCLUDE LN1CUSTOMER_TYPESI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LN1CUSTOMER_TYPESF...              " Subprograms
* INCLUDE LN1CUSTOMER_TYPESO...              " PBO-Modules
* INCLUDE LN1CUSTOMER_TYPESI...              " PAI-Modules

INCLUDE LN1CUSTOMER_TYPESI01.

INCLUDE LN1CUSTOMER_TYPESF01.
